
export const DIY_HOW_TO = [
    { l: "Step-by-Step Guide", f: "Task → Instructions" },
    { l: "DIY Project Plan", f: "Material → Steps" },
    { l: "Home Repair Manual", f: "Issue → Solution" },
    { l: "Instructional Template", f: "Step → Detail" },
    { l: "Crafting Tutorial", f: "Project → Procedure" },
    { l: "Tool Usage Guide", f: "Tool → Instruction" },
    { l: "Maintenance Checklist", f: "Task → Status" },
    { l: "Furniture Assembly Instructions", f: "Part → Step" },
    { l: "Home Improvement Notes", f: "Area → Task" },
    { l: "Safety Precautions Sheet", f: "Task → Risk" },
    { l: "Gardening Guide", f: "Plant → Care" },
    { l: "DIY Video Script", f: "Scene → Action" },
    { l: "Workshop Agenda", f: "Activity → Time" },
    { l: "Repair Log", f: "Item → Issue" },
    { l: "Tutorial Flowchart", f: "Step → Next Step" },
    { l: "Home Decor Plan", f: "Room → Style" },
    { l: "Craft Supplies List", f: "Item → Quantity" },
    { l: "DIY Experiment Notes", f: "Task → Result" },
    { l: "Cleaning Schedule", f: "Area → Frequency" },
    { l: "Painting Guide", f: "Surface → Technique" },
    { l: "Woodworking Plan", f: "Component → Steps" },
    { l: "Electrical Repair Notes", f: "Circuit → Action" },
    { l: "Plumbing Instruction Sheet", f: "Pipe → Step" },
    { l: "Craft Project Template", f: "Material → Step" },
    { l: "DIY Blog Post", f: "Topic → Tutorial" },
    { l: "Home Renovation Timeline", f: "Task → Date" },
    { l: "DIY Challenge Plan", f: "Task → Rules" },
    { l: "Repair Instruction Manual", f: "Device → Step" },
    { l: "Maintenance Tracker", f: "Task → Status" },
    { l: "Craft Workshop Plan", f: "Project → Activity" },
    { l: "DIY Safety Checklist", f: "Task → Completion" },
    { l: "Equipment Instruction Guide", f: "Tool → Usage" },
    { l: "Stepwise Guide for Painting", f: "Wall → Steps" },
    { l: "Repair Materials List", f: "Item → Quantity" },
    { l: "Gardening Calendar", f: "Task → Month" },
    { l: "Home Improvement Checklist", f: "Task → Status" },
    { l: "DIY Experiment Plan", f: "Hypothesis → Steps" },
    { l: "Repair Cost Estimation", f: "Part → Price" },
    { l: "Tool Inventory", f: "Item → Condition" },
    { l: "DIY Video Shooting Plan", f: "Scene → Action" },
    { l: "Assembly Diagram", f: "Component → Connection" },
    { l: "Crafting Technique Sheet", f: "Technique → Step" },
    { l: "Maintenance Manual", f: "System → Procedure" },
    { l: "Repair Feedback Form", f: "Task → Result" },
    { l: "DIY Workshop Materials", f: "Item → Quantity" },
    { l: "Instructional Notes", f: "Step → Detail" },
    { l: "Home Project Timeline", f: "Task → Duration" },
    { l: "Craft Template Sheet", f: "Project → Steps" },
    { l: "Safety Guidelines", f: "Task → Precaution" },
    { l: "Repair Flowchart", f: "Step → Outcome" },
    { l: "DIY Resource List", f: "Tool → Use" },
    { l: "Workshop Evaluation Form", f: "Activity → Feedback" },
    { l: "Painting Project Plan", f: "Surface → Color" },
    { l: "DIY Blog Draft", f: "Topic → Instructions" },
    { l: "Equipment Maintenance Log", f: "Tool → Date" },
    { l: "Home Upgrade Plan", f: "Area → Task" },
    { l: "Craft Tutorial Video", f: "Step → Description" },
    { l: "Repair Strategy Notes", f: "Issue → Solution" },
    { l: "Maintenance Checklist Template", f: "Task → Status" },
    { l: "DIY Experiment Result Sheet", f: "Task → Observation" },
    { l: "Craft Event Proposal", f: "Activity → Schedule" },
    { l: "Home Organization Plan", f: "Area → Arrangement" },
    { l: "Tool Safety Instruction", f: "Tool → Precaution" },
    { l: "DIY Quick Tips Sheet", f: "Task → Advice" },
    { l: "Repair Task Assignment", f: "Task → Person" },
    { l: "Workshop Agenda Template", f: "Session → Activity" },
    { l: "DIY Progress Tracker", f: "Task → Status" },
    { l: "Home Improvement Evaluation", f: "Task → Score" },
    { l: "Project Resource Allocation", f: "Task → Material" },
    { l: "Repair Completion Report", f: "Task → Result" }
];
