
export const FINANCE_ACCOUNTING = [
    { l: "Budget Report", f: "Category → Amount" },
    { l: "Expense Report", f: "Item → Cost" },
    { l: "Profit & Loss Statement", f: "Revenue → Expense" },
    { l: "Balance Sheet", f: "Asset → Liability" },
    { l: "Cash Flow Statement", f: "Inflow → Outflow" },
    { l: "Investment Proposal", f: "Opportunity → ROI" },
    { l: "Financial Forecast", f: "Quarter → Projection" },
    { l: "Audit Report", f: "Finding → Recommendation" },
    { l: "Tax Filing Document", f: "Form → Details" },
    { l: "Invoice", f: "Item → Total" },
    { l: "Quotation", f: "Requirement → Estimate" },
    { l: "Purchase Order", f: "Item → Quantity" },
    { l: "Account Reconciliation", f: "Transaction → Status" },
    { l: "Financial Statement Summary", f: "Metric → Analysis" },
    { l: "Risk Assessment", f: "Investment → Rating" },
    { l: "Credit Report", f: "Borrower → Score" },
    { l: "Loan Application", f: "Applicant → Details" },
    { l: "Debt Schedule", f: "Creditor → Amount" },
    { l: "Capital Expenditure Proposal", f: "Asset → Cost" },
    { l: "Shareholder Report", f: "Performance → Dividend" },
    { l: "Annual Financial Review", f: "Year → Highlights" },
    { l: "Budget Allocation Plan", f: "Department → Amount" },
    { l: "Payroll Sheet", f: "Employee → Salary" },
    { l: "Expense Approval Form", f: "Request → Decision" },
    { l: "Financial KPI Dashboard", f: "Metric → Value" },
    { l: "Cash Management Plan", f: "Account → Strategy" },
    { l: "Tax Audit Checklist", f: "Requirement → Status" },
    { l: "Accounting Policy Document", f: "Rule → Example" },
    { l: "Internal Control Report", f: "Control → Effectiveness" },
    { l: "Revenue Recognition Doc", f: "Transaction → Method" },
    { l: "Cost-Benefit Analysis", f: "Option → Result" },
    { l: "Accounting Ledger", f: "Account → Entry" },
    { l: "Bank Reconciliation Statement", f: "Transaction → Status" },
    { l: "Procurement Report", f: "Vendor → Spend" },
    { l: "Financial Ratio Analysis", f: "Metric → Interpretation" },
    { l: "Asset Depreciation Schedule", f: "Asset → Method" },
    { l: "Fundraising Proposal", f: "Source → Amount" },
    { l: "Capital Structure Analysis", f: "Source → Equity/Debt" },
    { l: "Cash Forecast", f: "Month → Amount" },
    { l: "Financial Scenario Plan", f: "Scenario → Result" },
    { l: "Equity Research Report", f: "Company → Valuation" },
    { l: "Portfolio Summary", f: "Asset → Allocation" },
    { l: "Expense Tracker", f: "Category → Amount" },
    { l: "Audit Trail", f: "Transaction → Action" },
    { l: "Profitability Analysis", f: "Product → Margin" },
    { l: "Cost Allocation Plan", f: "Department → Share" },
    { l: "Revenue Forecast", f: "Product → Projection" },
    { l: "Budget Review", f: "Period → Adjustment" },
    { l: "Financial Compliance Checklist", f: "Rule → Status" },
    { l: "Grant Financial Report", f: "Fund → Usage" },
    { l: "Tax Planning Document", f: "Year → Strategy" },
    { l: "Financial Summary Sheet", f: "Account → Balance" },
    { l: "Fund Report", f: "Investment → Yield" },
    { l: "Accounts Payable Sheet", f: "Supplier → Amount" },
    { l: "Accounts Receivable Sheet", f: "Customer → Amount" },
    { l: "Investment Performance Report", f: "Asset → Return" },
    { l: "Risk Register", f: "Item → Probability" },
    { l: "Financial Policy Memo", f: "Issue → Recommendation" },
    { l: "Treasury Report", f: "Cash → Liquidity" },
    { l: "Equity Distribution Plan", f: "Shareholder → Percentage" },
    { l: "Expense Policy", f: "Category → Limit" },
    { l: "Budget Template", f: "Category → Allocation" },
    { l: "Annual Audit Checklist", f: "Task → Status" },
    { l: "Profit Projection", f: "Product → Forecast" },
    { l: "Financial Plan Summary", f: "Objective → Strategy" }
];
