
export const FOOD_RECIPE = [
    { l: "Recipe Template", f: "Dish → Ingredients" },
    { l: "Cooking Procedure", f: "Step → Instruction" },
    { l: "Meal Plan", f: "Day → Meals" },
    { l: "Ingredient List", f: "Item → Quantity" },
    { l: "Nutritional Information Sheet", f: "Dish → Values" },
    { l: "Cooking Tips", f: "Topic → Suggestion" },
    { l: "Recipe Card", f: "Title → Steps" },
    { l: "Menu Plan", f: "Section → Dishes" },
    { l: "Shopping List", f: "Category → Item" },
    { l: "Kitchen Inventory", f: "Item → Quantity" },
    { l: "Cooking Blog Post", f: "Recipe → Story" },
    { l: "Culinary Review", f: "Dish → Rating" },
    { l: "Chef Notes", f: "Recipe → Adjustment" },
    { l: "Dietary Restriction Guide", f: "Restriction → Alternative" },
    { l: "Cooking Class Plan", f: "Topic → Activity" },
    { l: "Baking Procedure", f: "Step → Temperature" },
    { l: "Meal Prep Instructions", f: "Day → Recipes" },
    { l: "Food Safety Guidelines", f: "Procedure → Precaution" },
    { l: "Cooking Experiment Notes", f: "Recipe → Result" },
    { l: "Recipe Video Script", f: "Segment → Action" },
    { l: "Ingredient Substitution Guide", f: "Ingredient → Alternative" },
    { l: "Food Photography Plan", f: "Dish → Shot Angle" },
    { l: "Recipe Rating Sheet", f: "Dish → Score" },
    { l: "Seasonal Recipe Plan", f: "Season → Ingredients" },
    { l: "Cultural Cuisine Guide", f: "Dish → Region" },
    { l: "Cooking Competition Rules", f: "Task → Evaluation" },
    { l: "Cookbook Outline", f: "Chapter → Recipes" },
    { l: "Cooking Event Proposal", f: "Theme → Menu" },
    { l: "Food Blog Editorial", f: "Topic → Recipe" },
    { l: "Nutrition Plan", f: "Meal → Macro Count" },
    { l: "Restaurant Menu", f: "Section → Dish" },
    { l: "Cooking Challenge Plan", f: "Task → Rules" },
    { l: "Kitchen Workflow Chart", f: "Task → Step" },
    { l: "Food Preservation Guide", f: "Method → Duration" },
    { l: "Recipe Development Notes", f: "Dish → Experiment" },
    { l: "Dessert Menu", f: "Item → Ingredients" },
    { l: "Beverage Menu", f: "Drink → Ingredients" },
    { l: "Food Festival Plan", f: "Activity → Location" },
    { l: "Cooking Newsletter", f: "Tip → Recipe" },
    { l: "Chef’s Recommendation", f: "Dish → Reason" },
    { l: "Recipe Scaling Chart", f: "Ingredient → Amount" },
    { l: "Cooking Equipment Guide", f: "Tool → Usage" },
    { l: "Dietary Plan Summary", f: "Meal → Benefit" },
    { l: "Recipe Rating Form", f: "Dish → Score" },
    { l: "Ingredient Prep Checklist", f: "Item → Step" },
    { l: "Cooking Workshop Agenda", f: "Session → Activity" },
    { l: "Seasonal Ingredient List", f: "Month → Item" },
    { l: "Recipe Feedback Form", f: "Question → Response" },
    { l: "Food Safety Checklist", f: "Task → Status" },
    { l: "Cooking Procedure Flowchart", f: "Step → Next Step" },
    { l: "Meal Cost Calculation", f: "Dish → Total" },
    { l: "Cooking Style Comparison", f: "Technique → Advantage" },
    { l: "Culinary Experiment Log", f: "Recipe → Outcome" },
    { l: "Recipe Revision Notes", f: "Step → Adjustment" },
    { l: "Food Blog Draft", f: "Topic → Recipe" },
    { l: "Ingredient Storage Guide", f: "Item → Method" },
    { l: "Food Pairing Chart", f: "Ingredient → Pair" },
    { l: "Cooking Quiz", f: "Question → Answer" },
    { l: "Chef Interview Notes", f: "Question → Answer" },
    { l: "Recipe Book Table of Contents", f: "Chapter → Recipe" },
    { l: "Meal Planning Template", f: "Day → Dish" },
    { l: "Cooking Budget Plan", f: "Meal → Cost" },
    { l: "Food Packaging Guide", f: "Product → Instructions" },
    { l: "Menu Engineering Report", f: "Item → Profit" },
    { l: "Cooking Tip Sheet", f: "Topic → Advice" },
    { l: "Recipe Sharing Template", f: "Dish → Details" },
    { l: "Dietary Restriction Recipe", f: "Dish → Alternative" },
    { l: "Restaurant Recipe Card", f: "Dish → Steps" },
    { l: "Food Preparation Timeline", f: "Step → Time" },
    { l: "Culinary Event Report", f: "Activity → Outcome" },
    // New additions
    { l: "Recipe Template", f: "Ingredient → Quantity" },
    { l: "Menu Planning Sheet", f: "Meal → Dish" },
    { l: "Ingredient Inventory", f: "Item → Quantity" },
    { l: "Cooking Step Checklist", f: "Step → Action" },
    { l: "Recipe Development Notes", f: "Dish → Observation" },
    { l: "Nutritional Analysis Report", f: "Dish → Value" },
    { l: "Meal Prep Schedule", f: "Day → Dish" },
    { l: "Culinary Workshop Agenda", f: "Topic → Activity" },
    { l: "Kitchen Safety Guidelines", f: "Task → Precaution" },
    { l: "Recipe Feedback Form", f: "Dish → Comment" }
];
