
export const GOVERNMENT_POLICY = [
    { l: "Policy Proposal", f: "Issue → Solution" },
    { l: "Government Report", f: "Topic → Findings" },
    { l: "Legislative Bill", f: "Clause → Effect" },
    { l: "Public Notice", f: "Subject → Details" },
    { l: "Executive Order", f: "Purpose → Action" },
    { l: "Ordinance Draft", f: "Section → Requirement" },
    { l: "Regulatory Report", f: "Requirement → Compliance" },
    { l: "Government Budget", f: "Department → Allocation" },
    { l: "Policy Brief", f: "Issue → Recommendation" },
    { l: "Citizen Feedback Report", f: "Topic → Response" },
    { l: "Law Enforcement Report", f: "Incident → Action" },
    { l: "Public Consultation Notes", f: "Topic → Feedback" },
    { l: "Parliamentary Debate Summary", f: "Motion → Outcome" },
    { l: "Committee Report", f: "Finding → Suggestion" },
    { l: "Regulatory Impact Assessment", f: "Proposal → Effect" },
    { l: "Municipal Planning Report", f: "Zone → Recommendations" },
    { l: "Public Safety Plan", f: "Risk → Mitigation" },
    { l: "Environmental Policy", f: "Objective → Enforcement" },
    { l: "Education Policy", f: "Initiative → Implementation" },
    { l: "Healthcare Policy", f: "Measure → Expected Outcome" },
    { l: "Housing Report", f: "Need → Plan" },
    { l: "Transportation Report", f: "Route → Issue" },
    { l: "Government Performance Audit", f: "Metric → Result" },
    { l: "Census Report", f: "Data → Analysis" },
    { l: "Government Circular", f: "Instruction → Distribution" },
    { l: "Executive Memo", f: "Topic → Action" },
    { l: "National Development Plan", f: "Goal → Milestone" },
    { l: "Public Infrastructure Report", f: "Project → Status" },
    { l: "Policy Evaluation Report", f: "Initiative → Impact" },
    { l: "Social Program Report", f: "Beneficiaries → Outcome" },
    { l: "Environmental Impact Statement", f: "Project → Effects" },
    { l: "Energy Policy Document", f: "Objective → Plan" },
    { l: "Public Health Advisory", f: "Topic → Guidance" },
    { l: "Economic Report", f: "Sector → Trend" },
    { l: "Urban Planning Proposal", f: "Area → Guidelines" },
    { l: "Rural Development Plan", f: "Region → Initiative" },
    { l: "Safety Audit", f: "Facility → Findings" },
    { l: "Regulatory Compliance Memo", f: "Topic → Recommendation" },
    { l: "Legislative Summary", f: "Bill → Key Points" },
    { l: "Government Memorandum", f: "Department → Instruction" },
    { l: "Policy Implementation Checklist", f: "Step → Status" },
    { l: "Public Consultation Summary", f: "Issue → Feedback" },
    { l: "Legal Draft for Government", f: "Clause → Content" },
    { l: "Interagency Report", f: "Department → Finding" },
    { l: "Public Works Report", f: "Project → Progress" },
    { l: "Disaster Management Plan", f: "Scenario → Action" },
    { l: "Public Transport Policy", f: "Route → Regulation" },
    { l: "Health Department Report", f: "Condition → Measures" },
    { l: "Education Department Memo", f: "Policy → Implementation" },
    { l: "Municipal Inspection Report", f: "Issue → Outcome" },
    { l: "Governance Risk Assessment", f: "Risk → Mitigation" },
    { l: "Community Engagement Plan", f: "Activity → Timeline" },
    { l: "Regulatory Notice", f: "Agency → Requirement" },
    { l: "National Security Brief", f: "Threat → Response" },
    { l: "Legislative Briefing", f: "Issue → Position" },
    { l: "Public Procurement Plan", f: "Tender → Process" },
    { l: "Government Project Timeline", f: "Milestone → Deadline" },
    { l: "Policy Review Report", f: "Policy → Recommendation" },
    { l: "Administrative Report", f: "Task → Outcome" },
    { l: "Public Service Announcement", f: "Topic → Message" }
];
