
export const PHILANTHROPY_NGOS = [
    { l: "Grant Proposal", f: "Project → Budget" },
    { l: "Donation Campaign Plan", f: "Channel → Goal" },
    { l: "Volunteer Schedule", f: "Volunteer → Task" },
    { l: "NGO Annual Report", f: "Program → Result" },
    { l: "Fundraising Event Plan", f: "Activity → Step" },
    { l: "Impact Assessment Report", f: "Program → Outcome" },
    { l: "Donor Communication Template", f: "Message → Recipient" },
    { l: "Community Needs Assessment", f: "Area → Findings" },
    { l: "Project Monitoring Sheet", f: "Task → Status" },
    { l: "Volunteer Training Agenda", f: "Topic → Activity" },
    { l: "NGO Policy Document", f: "Rule → Implementation" },
    { l: "Fundraising Metrics Dashboard", f: "Metric → Value" },
    { l: "Project Proposal Template", f: "Initiative → Step" },
    { l: "Donor Feedback Form", f: "Question → Response" },
    { l: "NGO Program Timeline", f: "Task → Completion" },
    { l: "Volunteer Feedback Notes", f: "Volunteer → Comment" },
    { l: "Grant Application Checklist", f: "Item → Status" },
    { l: "Fundraising Campaign Timeline", f: "Activity → Date" },
    { l: "Community Outreach Plan", f: "Area → Action" },
    { l: "NGO Meeting Minutes", f: "Topic → Action" },
    { l: "Program Evaluation Template", f: "Indicator → Score" },
    { l: "Volunteer Assignment Sheet", f: "Task → Volunteer" },
    { l: "Donation Tracking Sheet", f: "Donor → Amount" },
    { l: "NGO Strategy Plan", f: "Initiative → Goal" },
    { l: "Fund Allocation Report", f: "Program → Amount" },
    { l: "Project Risk Assessment", f: "Risk → Mitigation" },
    { l: "NGO Workshop Agenda", f: "Topic → Activity" },
    { l: "Community Survey Template", f: "Question → Answer" },
    { l: "Impact Metrics Tracker", f: "Metric → Value" },
    { l: "Fundraising Proposal Draft", f: "Project → Budget" },
    { l: "NGO Newsletter", f: "Topic → Article" },
    { l: "Volunteer Recognition Plan", f: "Volunteer → Action" },
    { l: "Grant Report Template", f: "Program → Outcome" },
    { l: "Donor Retention Strategy", f: "Segment → Step" },
    { l: "NGO Event Budget", f: "Activity → Cost" },
    { l: "Community Partnership Plan", f: "Organization → Task" },
    { l: "Project Documentation Template", f: "Task → Step" },
    { l: "Volunteer Recruitment Notes", f: "Candidate → Observation" },
    { l: "NGO Workshop Feedback", f: "Participant → Comment" },
    { l: "Fundraising Goal Tracker", f: "Campaign → Value" },
    { l: "Program Implementation Timeline", f: "Task → Step" },
    { l: "Donor Engagement Dashboard", f: "Metric → Value" },
    { l: "NGO Policy Review Notes", f: "Policy → Comment" },
    { l: "Grant Proposal Evaluation", f: "Project → Score" },
    { l: "Volunteer Training Materials", f: "Topic → Content" },
    { l: "NGO Program Proposal", f: "Initiative → Goal" },
    { l: "Donation Campaign Metrics", f: "Channel → Result" },
    { l: "Community Engagement Report", f: "Activity → Outcome" },
    { l: "NGO Board Meeting Notes", f: "Topic → Decision" },
    { l: "Volunteer Performance Tracker", f: "Volunteer → Metric" },
    { l: "Fundraising Event Checklist", f: "Task → Status" },
    { l: "Project Impact Dashboard", f: "Metric → Value" },
    { l: "NGO Strategic Planning Notes", f: "Initiative → Step" },
    { l: "Donor Acknowledgment Letter", f: "Donor → Message" },
    { l: "Volunteer Program Outline", f: "Role → Responsibility" },
    { l: "NGO Annual Planning Calendar", f: "Month → Activity" },
    { l: "Grant Submission Notes", f: "Program → Detail" },
    { l: "Fundraising Campaign Budget", f: "Channel → Cost" },
    { l: "NGO Risk Mitigation Plan", f: "Risk → Action" },
    { l: "Volunteer Assignment Timeline", f: "Task → Completion" },
    { l: "Community Needs Report", f: "Area → Insight" },
    { l: "NGO Program Resource List", f: "Item → Usage" },
    { l: "Fundraising Event Planning Notes", f: "Task → Detail" },
    { l: "Donor Survey Template", f: "Question → Answer" },
    { l: "NGO Performance Report", f: "Program → Metric" },
    { l: "Volunteer Engagement Strategy", f: "Action → Timeline" },
    { l: "Project Milestone Tracker", f: "Task → Completion" },
    { l: "NGO Workshop Notes", f: "Topic → Detail" },
    { l: "Fundraising Campaign Archive", f: "Campaign → Result" },
    { l: "Donor Impact Report", f: "Donor → Outcome" }
];
