
export const PSYCHOLOGY_MENTAL_HEALTH = [
    { l: "Therapy Session Notes", f: "Client → Observation" },
    { l: "Psychological Assessment", f: "Test → Score" },
    { l: "Mental Health Plan", f: "Goal → Action" },
    { l: "Cognitive Behavioral Worksheet", f: "Exercise → Response" },
    { l: "Patient Intake Form", f: "Personal Info → History" },
    { l: "Counseling Progress Report", f: "Session → Outcome" },
    { l: "Case Study", f: "Patient → Analysis" },
    { l: "Psychological Research Proposal", f: "Hypothesis → Method" },
    { l: "Behavioral Observation Log", f: "Behavior → Frequency" },
    { l: "Mental Health Risk Assessment", f: "Factor → Severity" },
    { l: "Mood Tracking Sheet", f: "Date → Mood Score" },
    { l: "Therapy Homework Assignment", f: "Task → Instructions" },
    { l: "Group Therapy Plan", f: "Session → Activity" },
    { l: "Crisis Intervention Plan", f: "Situation → Action" },
    { l: "Psychotherapy Session Summary", f: "Client → Notes" },
    { l: "Mental Health Survey", f: "Question → Answer" },
    { l: "Cognitive Test Report", f: "Task → Result" },
    { l: "Treatment Plan", f: "Issue → Strategy" },
    { l: "Patient Feedback Form", f: "Question → Response" },
    { l: "Psychological Evaluation Report", f: "Client → Score" },
    { l: "Anxiety Management Plan", f: "Strategy → Steps" },
    { l: "Depression Screening Report", f: "Patient → Result" },
    { l: "Therapy Goal Setting Sheet", f: "Goal → Target" },
    { l: "Behavioral Intervention Plan", f: "Behavior → Technique" },
    { l: "Counseling Session Outline", f: "Topic → Method" },
    { l: "Mental Health Workshop Plan", f: "Topic → Activities" },
    { l: "Sleep Tracking Log", f: "Date → Hours" },
    { l: "Mindfulness Exercise Plan", f: "Task → Duration" },
    { l: "Stress Assessment Sheet", f: "Factor → Score" },
    { l: "Coping Skills Guide", f: "Situation → Technique" },
    { l: "Emotional Intelligence Assessment", f: "Domain → Score" },
    { l: "Trauma Recovery Plan", f: "Phase → Action" },
    { l: "Therapy Progress Tracker", f: "Session → Notes" },
    { l: "Psychiatric Evaluation Report", f: "Symptom → Rating" },
    { l: "Cognitive Function Assessment", f: "Task → Score" },
    { l: "Behavioral Therapy Plan", f: "Goal → Steps" },
    { l: "Psychoeducation Material", f: "Topic → Content" },
    { l: "Mental Health Newsletter", f: "Topic → Advice" },
    { l: "Patient Self-Assessment Form", f: "Question → Response" },
    { l: "Therapy Session Agenda", f: "Topic → Activity" },
    { l: "Counseling Referral Form", f: "Client → Specialist" },
    { l: "Risk Management Plan", f: "Client → Precaution" },
    { l: "Psychological Case Notes", f: "Client → Observation" },
    { l: "Psychiatric Treatment Summary", f: "Medication → Response" },
    { l: "Mental Health Program Proposal", f: "Initiative → Steps" },
    { l: "Behavioral Experiment Log", f: "Task → Result" },
    { l: "Therapy Evaluation Form", f: "Session → Feedback" },
    { l: "Cognitive Development Report", f: "Age → Score" },
    { l: "Mental Health Awareness Campaign", f: "Topic → Audience" },
    { l: "Psychometric Test Template", f: "Task → Score" },
    { l: "Counseling Policy Document", f: "Rule → Application" },
    { l: "Emotional Health Plan", f: "Goal → Technique" },
    { l: "Anxiety Tracking Log", f: "Date → Level" },
    { l: "Therapy Outcome Report", f: "Client → Progress" },
    { l: "Mental Health Research Notes", f: "Observation → Data" },
    { l: "Patient Support Plan", f: "Issue → Action" },
    { l: "Coping Strategy Worksheet", f: "Stressor → Response" },
    { l: "Psychiatric Medication Log", f: "Drug → Dosage" },
    { l: "Therapy Consent Form", f: "Procedure → Acknowledgment" },
    { l: "Mental Health Case Study Summary", f: "Patient → Outcome" }
];
