
export const SCIENCE_RESEARCH_DOCUMENTATION = [
    { l: "Research Proposal", f: "Hypothesis → Method" },
    { l: "Laboratory Experiment Plan", f: "Task → Step" },
    { l: "Scientific Paper", f: "Section → Content" },
    { l: "Experiment Observation Log", f: "Date → Result" },
    { l: "Data Analysis Report", f: "Dataset → Insight" },
    { l: "Research Ethics Checklist", f: "Task → Status" },
    { l: "Grant Proposal", f: "Project → Budget" },
    { l: "Laboratory Safety Guidelines", f: "Procedure → Precaution" },
    { l: "Experiment Protocol", f: "Step → Detail" },
    { l: "Field Research Notes", f: "Location → Observation" },
    { l: "Scientific Review Notes", f: "Paper → Comment" },
    { l: "Research Data Collection Sheet", f: "Variable → Value" },
    { l: "Experiment Timeline", f: "Task → Date" },
    { l: "Research Presentation Slides", f: "Topic → Slide Content" },
    { l: "Literature Review", f: "Topic → Summary" },
    { l: "Research Methodology Document", f: "Method → Detail" },
    { l: "Data Visualization Plan", f: "Dataset → Chart Type" },
    { l: "Experiment Hypothesis Tracker", f: "Hypothesis → Result" },
    { l: "Scientific Poster Template", f: "Section → Content" },
    { l: "Research Study Timeline", f: "Task → Completion" },
    { l: "Laboratory Logbook", f: "Task → Observation" },
    { l: "Peer Review Notes", f: "Paper → Comment" },
    { l: "Research Ethics Approval Form", f: "Project → Signature" },
    { l: "Data Collection Checklist", f: "Task → Status" },
    { l: "Statistical Analysis Plan", f: "Dataset → Test" },
    { l: "Experiment Result Sheet", f: "Task → Outcome" },
    { l: "Research Project Timeline", f: "Task → Milestone" },
    { l: "Literature Summary Notes", f: "Author → Findings" },
    { l: "Research Grant Application", f: "Proposal → Budget" },
    { l: "Scientific Experiment Flowchart", f: "Step → Next Step" },
    { l: "Field Study Plan", f: "Location → Task" },
    { l: "Data Quality Assessment", f: "Dataset → Issue" },
    { l: "Laboratory Equipment Checklist", f: "Item → Status" },
    { l: "Experiment Materials List", f: "Item → Quantity" },
    { l: "Research Collaboration Plan", f: "Partner → Role" },
    { l: "Research Workshop Agenda", f: "Session → Topic" },
    { l: "Research Progress Report", f: "Task → Result" },
    { l: "Laboratory Safety Audit", f: "Task → Status" },
    { l: "Experiment Analysis Report", f: "Variable → Outcome" },
    { l: "Data Management Plan", f: "Dataset → Procedure" },
    { l: "Research Method Comparison", f: "Method → Advantage" },
    { l: "Research Proposal Review", f: "Section → Comment" },
    { l: "Experiment Observation Sheet", f: "Task → Observation" },
    { l: "Scientific Journal Submission Checklist", f: "Item → Status" },
    { l: "Laboratory Experiment Notes", f: "Step → Observation" },
    { l: "Research Policy Document", f: "Rule → Application" },
    { l: "Data Collection Protocol", f: "Variable → Procedure" },
    { l: "Experiment Feedback Form", f: "Participant → Response" },
    { l: "Research Project Risk Assessment", f: "Risk → Mitigation" },
    { l: "Laboratory Procedure Template", f: "Task → Step" },
    { l: "Scientific Hypothesis Testing Plan", f: "Hypothesis → Method" },
    { l: "Research Dataset Documentation", f: "Dataset → Description" },
    { l: "Experiment Workflow Chart", f: "Step → Outcome" },
    { l: "Field Observation Template", f: "Location → Note" },
    { l: "Scientific Conference Paper", f: "Topic → Finding" },
    { l: "Research Evaluation Form", f: "Criterion → Score" },
    { l: "Experiment Resource Allocation", f: "Task → Resource" },
    { l: "Laboratory Experiment Timeline", f: "Task → Date" },
    { l: "Research Collaboration Notes", f: "Partner → Task" },
    { l: "Scientific Data Collection Plan", f: "Variable → Method" },
    { l: "Research Finding Summary", f: "Section → Result" },
    { l: "Experiment Design Document", f: "Task → Step" },
    { l: "Field Research Log", f: "Location → Observation" },
    { l: "Research Impact Report", f: "Study → Outcome" },
    { l: "Experiment Error Log", f: "Task → Issue" },
    { l: "Data Analysis Template", f: "Variable → Calculation" },
    { l: "Research Policy Review", f: "Document → Comment" },
    { l: "Laboratory Experiment Evaluation", f: "Step → Score" },
    { l: "Research Notes Archive", f: "Topic → Observation" },
    { l: "Scientific Study Progress Tracker", f: "Task → Status" }
];
