
export const SPORTS_FITNESS = [
    { l: "Training Plan", f: "Day → Exercises" },
    { l: "Workout Schedule", f: "Week → Routine" },
    { l: "Fitness Goal Tracker", f: "Goal → Measurement" },
    { l: "Athlete Profile", f: "Name → Stats" },
    { l: "Exercise Instruction Sheet", f: "Move → Steps" },
    { l: "Sports Event Plan", f: "Activity → Time" },
    { l: "Game Strategy Guide", f: "Team → Plan" },
    { l: "Match Report", f: "Team → Score" },
    { l: "Tournament Schedule", f: "Match → Date" },
    { l: "Fitness Progress Log", f: "Date → Metric" },
    { l: "Sports Training Notes", f: "Drill → Observations" },
    { l: "Nutrition for Athletes", f: "Meal → Macro" },
    { l: "Injury Report", f: "Player → Status" },
    { l: "Recovery Plan", f: "Athlete → Steps" },
    { l: "Strength Training Plan", f: "Exercise → Sets" },
    { l: "Cardio Plan", f: "Session → Duration" },
    { l: "Flexibility Routine", f: "Stretch → Duration" },
    { l: "Team Roster", f: "Player → Position" },
    { l: "Match Analysis", f: "Event → Result" },
    { l: "Sports Equipment Checklist", f: "Item → Status" },
    { l: "Physical Assessment Report", f: "Athlete → Score" },
    { l: "Coaching Notes", f: "Drill → Observation" },
    { l: "Game Tactics Sheet", f: "Position → Action" },
    { l: "Competition Entry Form", f: "Participant → Event" },
    { l: "Performance Review", f: "Athlete → Metric" },
    { l: "Sports Policy Document", f: "Rule → Detail" },
    { l: "League Standing Table", f: "Team → Points" },
    { l: "Training Feedback Form", f: "Drill → Response" },
    { l: "Fitness Workshop Plan", f: "Topic → Session" },
    { l: "Strength Evaluation Sheet", f: "Exercise → Score" },
    { l: "Endurance Test Report", f: "Participant → Result" },
    { l: "Injury Prevention Guide", f: "Exercise → Advice" },
    { l: "Fitness Class Plan", f: "Session → Routine" },
    { l: "Sports Blog Post", f: "Topic → Analysis" },
    { l: "Game Recap Summary", f: "Match → Highlights" },
    { l: "Athletic Award Nomination", f: "Athlete → Achievement" },
    { l: "Practice Session Report", f: "Activity → Outcome" },
    { l: "Coaching Strategy Memo", f: "Focus → Action" },
    { l: "Player Scouting Report", f: "Player → Skill" },
    { l: "Sports Event Poster", f: "Match → Date" },
    { l: "Training Log Template", f: "Date → Exercise" },
    { l: "Fitness Program Evaluation", f: "Metric → Result" },
    { l: "Sports Marketing Plan", f: "Event → Promotion" },
    { l: "Team Meeting Agenda", f: "Topic → Time" },
    { l: "Athletic Sponsorship Proposal", f: "Brand → Benefit" },
    { l: "Competition Rulebook", f: "Rule → Explanation" },
    { l: "Exercise Tutorial Script", f: "Move → Instruction" },
    { l: "Sports Quiz", f: "Question → Answer" },
    { l: "Fitness Newsletter", f: "Topic → Advice" },
    { l: "Team Formation Plan", f: "Position → Player" },
    { l: "Game Playbook", f: "Play → Diagram" },
    { l: "Athletic Health Checklist", f: "Task → Status" },
    { l: "Sports Injury Log", f: "Type → Treatment" },
    { l: "Fitness App Content", f: "Module → Activity" },
    { l: "Exercise Challenge Plan", f: "Activity → Duration" },
    { l: "Training Evaluation Form", f: "Drill → Feedback" },
    { l: "Physical Fitness Report", f: "Metric → Assessment" },
    { l: "Sports Event Summary", f: "Match → Result" },
    { l: "Athlete Interview Notes", f: "Question → Response" },
    { l: "Coaching Guide", f: "Topic → Technique" },
    { l: "Pre-Game Checklist", f: "Task → Status" },
    { l: "Team Performance Dashboard", f: "Metric → Value" },
    { l: "Exercise Equipment Guide", f: "Tool → Usage" },
    { l: "Fitness Competition Report", f: "Event → Winner" },
    { l: "Endurance Training Log", f: "Session → Result" }
];
