
export const LEGAL_REGULATORY = [
    { l: "Contract Draft", f: "Parties → Terms" },
    { l: "Lease Agreement", f: "Lessor → Lessee Terms" },
    { l: "Non-Disclosure Agreement", f: "Clauses → Duration" },
    { l: "Employment Contract", f: "Position → Salary" },
    { l: "Partnership Agreement", f: "Partners → Roles" },
    { l: "Memorandum of Understanding", f: "Intent → Scope" },
    { l: "Litigation Brief", f: "Facts → Arguments" },
    { l: "Court Filing", f: "Case Summary → Supporting Evidence" },
    { l: "Legal Opinion", f: "Facts → Recommendation" },
    { l: "Compliance Checklist", f: "Regulation → Status" },
    { l: "Regulatory Report", f: "Standard → Compliance Notes" },
    { l: "Intellectual Property Filing", f: "Patent → Claims" },
    { l: "Copyright Application", f: "Work → Ownership Details" },
    { l: "Trademark Registration", f: "Mark → Class" },
    { l: "Legal Notice", f: "Recipient → Demand" },
    { l: "Cease & Desist Letter", f: "Issue → Action Required" },
    { l: "Settlement Agreement", f: "Parties → Terms" },
    { l: "Arbitration Report", f: "Dispute → Outcome" },
    { l: "Legal Memo", f: "Issue → Analysis" },
    { l: "Risk Management Document", f: "Risk → Mitigation" },
    { l: "Court Judgment Summary", f: "Case → Ruling" },
    { l: "Contract Amendment", f: "Clause → Revision" },
    { l: "Terms & Conditions", f: "Section → Details" },
    { l: "Privacy Policy", f: "Data Type → Handling" },
    { l: "Licensing Agreement", f: "Licensee → Permissions" },
    { l: "Franchise Agreement", f: "Franchisor → Obligations" },
    { l: "Power of Attorney", f: "Principal → Powers" },
    { l: "Will & Testament", f: "Beneficiaries → Distribution" },
    { l: "Trust Document", f: "Trustee → Assets" },
    { l: "Legal Case Timeline", f: "Event → Date" },
    { l: "Evidence Log", f: "Item → Description" },
    { l: "Witness Statement", f: "Person → Account" },
    { l: "Summons", f: "Defendant → Court Details" },
    { l: "Injunction Request", f: "Action → Justification" },
    { l: "Legal Checklist", f: "Requirement → Status" },
    { l: "Contract Review Notes", f: "Clause → Comments" },
    { l: "Regulatory Impact Assessment", f: "Change → Effect" },
    { l: "Legal Draft Template", f: "Section → Content" },
    { l: "Code of Conduct", f: "Rule → Explanation" },
    { l: "Litigation Strategy", f: "Issue → Approach" },
    { l: "Legal Risk Register", f: "Risk → Severity" },
    { l: "Legal Research Notes", f: "Case → Citation" },
    { l: "Case Law Summary", f: "Precedent → Application" },
    { l: "Settlement Proposal", f: "Terms → Benefits" },
    { l: "Legal Briefing", f: "Issue → Recommended Action" },
    { l: "Statutory Compliance Report", f: "Requirement → Evidence" },
    { l: "Government Filing", f: "Form → Submission Details" },
    { l: "Legal Audit", f: "Document → Compliance Check" },
    { l: "Legal FAQ", f: "Question → Answer" },
    { l: "Court Transcript", f: "Speaker → Statement" },
    { l: "Legal Reference Guide", f: "Topic → Case Example" },
    { l: "Policy Draft", f: "Clause → Explanation" },
    { l: "Legal Notice of Termination", f: "Party → Reason" },
    { l: "Legal Risk Analysis", f: "Scenario → Recommendation" },
    { l: "Licensing Terms", f: "Rights → Restrictions" },
    { l: "Legal Advisory", f: "Topic → Guidance" },
    { l: "Court Motion", f: "Request → Supporting Facts" },
    { l: "Legal Opinion Letter", f: "Issue → Conclusion" },
    { l: "Regulatory Filing", f: "Agency → Details" },
    { l: "Compliance Report Summary", f: "Requirement → Status" }
];
