
export const RESEARCH_ACADEMIC = [
    { l: "Research Paper", f: "Method → Results" },
    { l: "Scientific Article", f: "Abstract → Findings" },
    { l: "Academic Essay", f: "Thesis → Evidence" },
    { l: "Case Study", f: "Background → Analysis" },
    { l: "Literature Review", f: "Themes → Gaps" },
    { l: "Meta-analysis", f: "Studies → Aggregated Results" },
    { l: "Research Proposal", f: "Problem Statement → Methodology" },
    { l: "Dissertation", f: "Introduction → Literature Review" },
    { l: "Thesis", f: "Hypothesis → Testing" },
    { l: "Lab Report", f: "Procedure → Observations" },
    { l: "Field Study", f: "Setup → Observations" },
    { l: "Experiment Report", f: "Variables → Outcomes" },
    { l: "Data Analysis Report", f: "Dataset → Interpretation" },
    { l: "Statistical Report", f: "Metrics → Conclusion" },
    { l: "Ethnographic Study", f: "Context → Behavior Patterns" },
    { l: "Survey Report", f: "Responses → Insights" },
    { l: "Interview Analysis", f: "Transcripts → Themes" },
    { l: "Scientific Review", f: "Topic → Evidence Summary" },
    { l: "White Paper", f: "Problem → Solutions" },
    { l: "Scholarly Commentary", f: "Claim → Supporting Arguments" },
    { l: "Annotated Bibliography", f: "Source Citation → Summary" },
    { l: "Academic Abstract", f: "Topic → Key Findings" },
    { l: "Technical Review", f: "Technology → Evaluation" },
    { l: "Conceptual Framework", f: "Concepts → Relationships" },
    { l: "Hypothesis Document", f: "Prediction → Rationale" },
    { l: "Policy Research", f: "Issue → Recommendations" },
    { l: "Comparative Study", f: "Subjects → Comparison" },
    { l: "STEM Report", f: "Concept → Application" },
    { l: "Analytical Essay", f: "Claim → Breakdown" },
    { l: "Reflective Essay", f: "Experience → Reflection" },
    { l: "Position Paper", f: "Stance → Argument" },
    { l: "Critical Analysis", f: "Work → Critique" },
    { l: "Theory Paper", f: "Concept → Applications" },
    { l: "Philosophical Essay", f: "Question → Reasoning" },
    { l: "Debate Brief", f: "Claim → Evidence" },
    { l: "Study Notes", f: "Topic → Summary" },
    { l: "Flashcard Set", f: "Term → Definition" },
    { l: "Scholarly Outline", f: "Topic → Subsections" },
    { l: "Research Timeline", f: "Milestones → Expected Results" },
    { l: "Peer Review Document", f: "Paper Summary → Evaluation" }
];
