
export const ARCHITECTURE_CONSTRUCTION = [
    { l: "Building Blueprint", f: "Floor → Layout" },
    { l: "Architectural Plan", f: "Section → Dimensions" },
    { l: "Structural Design", f: "Beam → Load" },
    { l: "Elevation Drawing", f: "Facade → Detail" },
    { l: "Floor Plan", f: "Room → Function" },
    { l: "Site Plan", f: "Boundary → Features" },
    { l: "Construction Schedule", f: "Task → Duration" },
    { l: "Material Specification", f: "Item → Quantity" },
    { l: "Cost Estimation Sheet", f: "Component → Price" },
    { l: "Building Permit Application", f: "Project → Approval" },
    { l: "Project Proposal", f: "Scope → Deliverables" },
    { l: "Feasibility Study", f: "Site → Evaluation" },
    { l: "Construction Progress Report", f: "Date → Milestone" },
    { l: "Contractor Agreement", f: "Party → Responsibility" },
    { l: "Safety Plan", f: "Risk → Procedure" },
    { l: "Inspection Report", f: "Component → Status" },
    { l: "Building Audit", f: "Element → Compliance" },
    { l: "Structural Analysis", f: "Element → Result" },
    { l: "Environmental Impact Assessment", f: "Factor → Effect" },
    { l: "Interior Design Plan", f: "Room → Elements" },
    { l: "Landscape Design", f: "Area → Features" },
    { l: "Renovation Plan", f: "Space → Upgrade" },
    { l: "Urban Planning Proposal", f: "Area → Usage" },
    { l: "Project Timeline", f: "Phase → Deadline" },
    { l: "Material Procurement List", f: "Item → Supplier" },
    { l: "Cost-Benefit Analysis", f: "Option → Outcome" },
    { l: "Risk Register", f: "Issue → Mitigation" },
    { l: "Construction Quality Checklist", f: "Item → Status" },
    { l: "Sustainability Report", f: "Feature → Rating" },
    { l: "Energy Efficiency Plan", f: "Measure → Effect" },
    { l: "HVAC Design Document", f: "Component → Spec" },
    { l: "Plumbing Layout", f: "Pipe → Route" },
    { l: "Electrical Plan", f: "Circuit → Load" },
    { l: "Fire Safety Plan", f: "Area → Procedure" },
    { l: "Foundation Design", f: "Type → Load Capacity" },
    { l: "Roof Design", f: "Material → Specification" },
    { l: "Facade Study", f: "Material → Aesthetic" },
    { l: "Lighting Plan", f: "Area → Intensity" },
    { l: "Acoustics Plan", f: "Space → Specification" },
    { l: "Building Maintenance Schedule", f: "Task → Frequency" },
    { l: "Construction Site Log", f: "Date → Activity" },
    { l: "Contractor Performance Report", f: "Task → Evaluation" },
    { l: "Interior Material List", f: "Item → Quantity" },
    { l: "Architectural Render", f: "View → Detail" },
    { l: "3D Model Summary", f: "Component → Features" },
    { l: "Structural Load Calculation", f: "Component → Result" },
    { l: "Construction Memo", f: "Issue → Resolution" },
    { l: "Compliance Report", f: "Standard → Status" },
    { l: "Warranty Document", f: "Component → Period" },
    { l: "Building User Manual", f: "System → Instructions" },
    { l: "Permit Renewal Form", f: "Project → Deadline" },
    { l: "Site Safety Checklist", f: "Task → Status" },
    { l: "Landscape Maintenance Plan", f: "Task → Frequency" },
    { l: "Construction Risk Assessment", f: "Hazard → Impact" },
    { l: "Project Handover Document", f: "Component → Detail" },
    { l: "Material Testing Report", f: "Sample → Result" },
    { l: "Work Order", f: "Task → Assignment" },
    { l: "Construction Payment Schedule", f: "Milestone → Amount" },
    { l: "Architectural Guideline", f: "Rule → Example" },
    { l: "Sustainability Checklist", f: "Standard → Compliance" },
    { l: "Structural Inspection", f: "Component → Finding" },
    { l: "Design Revision Notes", f: "Issue → Change" },
    { l: "Contractor Logbook", f: "Date → Task" },
    { l: "Construction Progress Dashboard", f: "Metric → Status" },
    { l: "Final Handover Report", f: "Component → Condition" }
];
