
export const ARTS_PERFORMING_ARTS = [
    { l: "Theater Script", f: "Act → Scene" },
    { l: "Performance Plan", f: "Performer → Cue" },
    { l: "Art Exhibit Proposal", f: "Theme → Display" },
    { l: "Dance Choreography Notes", f: "Step → Count" },
    { l: "Music Score Sheet", f: "Part → Measure" },
    { l: "Rehearsal Schedule", f: "Date → Activity" },
    { l: "Stage Lighting Plan", f: "Scene → Setup" },
    { l: "Costume Design Sheet", f: "Character → Outfit" },
    { l: "Script Revision Notes", f: "Scene → Change" },
    { l: "Art Installation Plan", f: "Artwork → Position" },
    { l: "Performance Feedback Form", f: "Question → Response" },
    { l: "Theater Production Timeline", f: "Task → Date" },
    { l: "Music Album Tracklist", f: "Track → Duration" },
    { l: "Rehearsal Notes", f: "Performer → Observation" },
    { l: "Stage Blocking Diagram", f: "Actor → Position" },
    { l: "Art Critique Report", f: "Piece → Comment" },
    { l: "Set Design Blueprint", f: "Scene → Element" },
    { l: "Performance Evaluation Form", f: "Performer → Score" },
    { l: "Music Recording Plan", f: "Track → Instrument" },
    { l: "Choreography Flowchart", f: "Move → Sequence" },
    { l: "Theater Program Draft", f: "Scene → Description" },
    { l: "Artist Statement", f: "Work → Intent" },
    { l: "Costume Inventory", f: "Item → Quantity" },
    { l: "Rehearsal Attendance Sheet", f: "Performer → Status" },
    { l: "Stage Prop List", f: "Prop → Scene" },
    { l: "Art Workshop Agenda", f: "Topic → Activity" },
    { l: "Music Production Timeline", f: "Task → Deadline" },
    { l: "Performance Marketing Plan", f: "Medium → Content" },
    { l: "Script Annotation Notes", f: "Scene → Comment" },
    { l: "Art Exhibition Timeline", f: "Task → Completion" },
    { l: "Stage Safety Guidelines", f: "Task → Precaution" },
    { l: "Music Sheet Arrangement", f: "Instrument → Part" },
    { l: "Performer Feedback Log", f: "Performer → Note" },
    { l: "Theater Poster Design", f: "Element → Detail" },
    { l: "Art Display Layout", f: "Piece → Position" },
    { l: "Performance Ticketing Plan", f: "Seat → Price" },
    { l: "Stage Equipment Checklist", f: "Item → Status" },
    { l: "Music Video Script", f: "Scene → Shot" },
    { l: "Theater Production Budget", f: "Department → Cost" },
    { l: "Choreography Notes", f: "Move → Count" },
    { l: "Music Collaboration Plan", f: "Artist → Track" },
    { l: "Art Supply Inventory", f: "Material → Quantity" },
    { l: "Performance Program Script", f: "Segment → Cue" },
    { l: "Stage Crew Assignment", f: "Crew → Task" },
    { l: "Theater Review Template", f: "Scene → Rating" },
    { l: "Art Installation Safety Plan", f: "Task → Precaution" },
    { l: "Music Album Production Notes", f: "Track → Task" },
    { l: "Costume Design Revision", f: "Character → Update" },
    { l: "Stage Lighting Setup Checklist", f: "Light → Position" },
    { l: "Rehearsal Planning Template", f: "Date → Task" },
    { l: "Performance Recording Log", f: "Scene → Take" },
    { l: "Art Criticism Essay", f: "Work → Analysis" },
    { l: "Music Sheet Revision Notes", f: "Part → Correction" },
    { l: "Stage Management Notes", f: "Task → Observation" },
    { l: "Theater Program Layout", f: "Section → Content" },
    { l: "Art Workshop Materials List", f: "Item → Quantity" },
    { l: "Performance Promotion Schedule", f: "Medium → Date" },
    { l: "Choreography Revision Notes", f: "Move → Change" },
    { l: "Music Session Planning", f: "Track → Instrument" },
    { l: "Set Construction Timeline", f: "Task → Date" },
    { l: "Art Event Proposal", f: "Theme → Schedule" },
    { l: "Stage Prop Arrangement Diagram", f: "Scene → Position" },
    { l: "Music Production Budget", f: "Track → Cost" },
    { l: "Rehearsal Feedback Form", f: "Performer → Comment" },
    { l: "Performance Metrics Dashboard", f: "Metric → Value" },
    { l: "Art Installation Documentation", f: "Piece → Notes" },
    { l: "Music Practice Log", f: "Performer → Time" },
    { l: "Stage Equipment Maintenance Plan", f: "Item → Task" },
    { l: "Theater Production Checklist", f: "Task → Status" },
    { l: "Choreography Performance Notes", f: "Move → Comment" },
    { l: "Art Exhibit Visitor Feedback", f: "Question → Response" },
    { l: "Performance Timeline", f: "Scene → Action" },
    { l: "Music Arrangement Template", f: "Track → Part" },
    { l: "Stage Lighting Adjustment Log", f: "Light → Setting" },
    { l: "Theater Evaluation Report", f: "Production → Score" }
];
