
export const BUSINESS_MANAGEMENT = [
    { l: "Business Plan", f: "Executive Summary → Strategy" },
    { l: "Startup Pitch", f: "Problem → Value Proposition" },
    { l: "Product Pitch", f: "Feature → Benefit" },
    { l: "Company Profile", f: "Overview → Services" },
    { l: "SWOT Analysis", f: "Strengths → Weaknesses" },
    { l: "Competitive Analysis", f: "Competitor → Insights" },
    { l: "Market Research", f: "Trend → Forecast" },
    { l: "Feasibility Study", f: "Assessment → Conclusion" },
    { l: "Business Report", f: "Summary → Insights" },
    { l: "Annual Report", f: "Highlights → Performance" },
    { l: "Quarterly Report", f: "Metrics → Analysis" },
    { l: "Financial Statement", f: "Accounts → Totals" },
    { l: "Budget Plan", f: "Category → Allocations" },
    { l: "Profit & Loss Sheet", f: "Revenue → Expense" },
    { l: "Risk Assessment", f: "Hazard → Mitigation" },
    { l: "Compliance Report", f: "Requirement → Status" },
    { l: "Audit Report", f: "Findings → Recommendations" },
    { l: "Strategic Plan", f: "Goal → To-Do Steps" },
    { l: "Operations Manual", f: "Task → Steps" },
    { l: "Standard Operating Procedure", f: "Step → Compliance Notes" },
    { l: "Meeting Agenda", f: "Topic → Time Block" },
    { l: "Meeting Minutes", f: "Discussion → Action Item" },
    { l: "Organizational Chart", f: "Role → Sub-Role" },
    { l: "Employee Handbook", f: "Policy → Rules" },
    { l: "Performance Review", f: "Strength → Improvement" },
    { l: "Hiring Plan", f: "Role → Requirements" },
    { l: "Interview Evaluation", f: "Candidate → Score" },
    { l: "Training Plan", f: "Module → Exercises" },
    { l: "Onboarding Checklist", f: "Step → Requirements" },
    { l: "Sales Report", f: "Product → Metrics" },
    { l: "Sales Pitch", f: "Feature → Benefit" },
    { l: "Marketing Plan", f: "Campaign → Channels" },
    { l: "Campaign Proposal", f: "Objective → Strategy" },
    { l: "Customer Journey Map", f: "Stage → Touchpoint" },
    { l: "CRM Notes", f: "Client → Next Action" },
    { l: "Business Case", f: "Problem → ROI" },
    { l: "Contract", f: "Term → Obligation" },
    { l: "Agreement", f: "Parties → Responsibilities" },
    { l: "Memorandum", f: "Issue → Statement" },
    { l: "Non-disclosure Agreement", f: "Clause → Conditions" },
    { l: "Invoice", f: "Item → Total" },
    { l: "Quotation", f: "Requirement → Estimate" },
    { l: "Purchase Order", f: "Item → Quantity" },
    { l: "Supplier Report", f: "Vendor → Evaluation" },
    { l: "Inventory Report", f: "Item → Stock Level" },
    { l: "Logistics Plan", f: "Route → Schedule" },
    { l: "Shipment Report", f: "Package → Status" },
    { l: "Customer Support Summary", f: "Issue → Resolution" },
    { l: "Call Log", f: "Caller → Summary" },
    { l: "Ticket Report", f: "Issue → Fix" },
    { l: "Partnership Proposal", f: "Synergy → Benefits" },
    { l: "Event Plan", f: "Agenda → Requirements" },
    { l: "Brand Guide", f: "Element → Rules" },
    { l: "Product Requirement", f: "Feature → Behavior" },
    { l: "Value Proposition Canvas", f: "Customer → Benefit" },
    { l: "User Persona", f: "Profile → Needs" },
    { l: "OKR Document", f: "Objective → Key Result" },
    { l: "KPI Report", f: "Metric → Performance" },
    { l: "Risk Log", f: "Issue → Severity" },
    { l: "Governance Document", f: "Rule → Procedure" },
    { l: "Venture Capital Proposal", f: "Problem → Investment Ask" },
    { l: "Startup Financial Plan", f: "Revenue → Forecast" },
    { l: "Investor Report", f: "Company → Metrics" },
    { l: "Pitch Deck Slide", f: "Topic → Notes" },
    { l: "Marketing Copy Plan", f: "Headline → Body" },
    { l: "Branding Proposal", f: "Concept → Application" },
    { l: "Social Media Strategy", f: "Channel → Content Type" },
    { l: "Market Entry Plan", f: "Region → Approach" },
    { l: "Product Launch Plan", f: "Milestone → Responsible Person" },
    { l: "Investor Update", f: "Status → Insights" },
    { l: "Board Meeting Packet", f: "Section → Notes" },
    { l: "KPI Dashboard", f: "Metric → Target" },
    { l: "Customer Retention Plan", f: "Strategy → Steps" },
    { l: "Sales Funnel Map", f: "Stage → Action" },
    { l: "Account Management Plan", f: "Client → Action" },
    { l: "Revenue Projection", f: "Month → Expected Income" },
    { l: "Cost Analysis", f: "Category → Amount" },
    { l: "Operational Efficiency Report", f: "Task → Improvement" },
    { l: "Procurement Plan", f: "Item → Supplier" },
    { l: "Vendor Assessment", f: "Criteria → Score" },
    { l: "Risk Mitigation Log", f: "Risk → Strategy" },
    { l: "Compliance Checklist", f: "Rule → Status" },
    { l: "Policy Draft", f: "Section → Explanation" },
    { l: "Corporate Governance Sheet", f: "Committee → Responsibility" },
    { l: "Contract Clause Tracker", f: "Clause → Status" },
    { l: "NDA Draft", f: "Clause → Condition" },
    { l: "Agreement Log", f: "Term → Effective Date" },
    { l: "Partnership Brief", f: "Benefit → Responsibility" },
    { l: "Franchise Plan", f: "Region → Operation Steps" },
    { l: "Event Budget", f: "Item → Cost" },
    { l: "Sponsorship Proposal", f: "Brand → Value" },
    { l: "Marketing Campaign Tracker", f: "Channel → Metrics" },
    { l: "PR Release Draft", f: "Statement → Quote" },
    { l: "Advertisement Script", f: "Visual → Copy" },
    { l: "Brand Messaging Doc", f: "Core Idea → Variants" },
    { l: "Content Marketing Plan", f: "Topic → Format" },
    { l: "Blog Calendar", f: "Date → Post Idea" },
    { l: "Email Campaign", f: "Subject → Body" },
    { l: "Lead Generation Plan", f: "Step → Outcome" },
    { l: "Affiliate Program Tracker", f: "Partner → Commission" },
    { l: "Loyalty Program Plan", f: "Tier → Benefit" },
    { l: "Customer Survey", f: "Question → Response" },
    { l: "Feedback Summary", f: "Topic → Action" },
    { l: "Customer Persona", f: "Demographic → Behavior" },
    { l: "Target Market Doc", f: "Segment → Strategy" },
    { l: "Competitive Matrix", f: "Competitor → Feature" },
    { l: "SWOT Expansion", f: "Category → Detail" },
    { l: "PEST Analysis", f: "Factor → Impact" },
    { l: "Scenario Planning", f: "Event → Response" },
    { l: "Strategic Roadmap", f: "Quarter → Milestone" },
    { l: "Product Backlog", f: "Feature → Priority" },
    { l: "Release Planning", f: "Version → Scope" },
    { l: "Sprint Plan", f: "Task → Assignee" },
    { l: "Kanban Board", f: "Card → Status" },
    { l: "Revenue Tracker", f: "Source → Amount" },
    { l: "Profit Margin Analysis", f: "Product → Percent" },
    { l: "Cash Flow Projection", f: "Period → Amount" },
    { l: "Expense Tracker", f: "Category → Value" },
    { l: "Investment Memo", f: "Opportunity → Justification" },
    { l: "IPO Preparation", f: "Section → Requirement" },
    { l: "M&A Due Diligence", f: "Area → Notes" },
    { l: "Valuation Report", f: "Asset → Value" },
    { l: "Loan Proposal", f: "Purpose → Collateral" },
    { l: "Debt Repayment Plan", f: "Amount → Schedule" },
    { l: "Financial Forecast", f: "Metric → Assumptions" },
    { l: "Expense Approval Log", f: "Request → Status" },
    { l: "Vendor Contract Tracker", f: "Vendor → Expiry" },
    { l: "Employee Benefits Plan", f: "Option → Details" },
    { l: "HR Policy Draft", f: "Section → Explanation" },
    { l: "Performance Incentive Plan", f: "Metric → Reward" },
    { l: "Employee Review Tracker", f: "Metric → Score" },
    { l: "Talent Acquisition Plan", f: "Role → Source" },
    { l: "Workforce Analysis", f: "Department → Needs" },
    { l: "Succession Plan", f: "Role → Candidate" },
    { l: "Internal Communication Plan", f: "Topic → Channel" },
    { l: "Crisis Management Plan", f: "Scenario → Action" },
    { l: "PR Crisis Script", f: "Event → Response" },
    { l: "Media Monitoring Report", f: "Outlet → Coverage" },
    { l: "Press Brief", f: "Topic → Key Points" },
    { l: "Stakeholder Map", f: "Stakeholder → Influence" },
    { l: "Regulatory Compliance Plan", f: "Requirement → Action" },
    { l: "Tax Compliance Tracker", f: "Jurisdiction → Status" },
    { l: "Insurance Coverage Plan", f: "Policy → Details" },
    { l: "Audit Trail", f: "Transaction → Reviewer" },
    { l: "IT Asset Plan", f: "Device → Status" },
    { l: "Data Protection Policy", f: "Rule → Control" },
    { l: "Cybersecurity Incident Plan", f: "Threat → Action" },
    { l: "Business Continuity Plan", f: "Scenario → Step" },
    { l: "Disaster Recovery Plan", f: "System → Action" },
    { l: "Emergency Communication Plan", f: "Channel → Recipient" },
    { l: "Operational Risk Register", f: "Risk → Likelihood" },
    { l: "KPI Benchmark", f: "Metric → Target" },
    { l: "Process Optimization Plan", f: "Process → Action" },
    { l: "Workflow Diagram", f: "Step → Next Step" },
    { l: "Task Delegation Sheet", f: "Task → Owner" },
    { l: "Project Charter", f: "Objective → Deliverables" },
    { l: "Initiative Tracker", f: "Project → Status" },
    { l: "Program Evaluation Plan", f: "Metric → Measure" },
    { l: "Business Impact Analysis", f: "Activity → Effect" },
    { l: "Operational Audit", f: "Task → Finding" }
];
