
export const BUSINESS_ENTREPRENEURSHIP = [
    { l: "Business Plan", f: "Section → Detail" },
    { l: "Startup Pitch Deck", f: "Slide → Content" },
    { l: "Market Analysis Report", f: "Market → Insight" },
    { l: "Financial Forecast", f: "Period → Metric" },
    { l: "Investor Proposal", f: "Opportunity → Benefit" },
    { l: "Business Strategy Plan", f: "Goal → Action" },
    { l: "Revenue Model Document", f: "Product → Revenue" },
    { l: "Competitor Analysis", f: "Competitor → Strength" },
    { l: "Marketing Campaign Plan", f: "Channel → Message" },
    { l: "Customer Feedback Form", f: "Question → Response" },
    { l: "Product Development Timeline", f: "Feature → Deadline" },
    { l: "Sales Forecast Sheet", f: "Product → Amount" },
    { l: "Business Process Map", f: "Task → Step" },
    { l: "Operational Guidelines", f: "Department → Instruction" },
    { l: "Startup Roadmap", f: "Phase → Task" },
    { l: "Business Model Canvas", f: "Component → Detail" },
    { l: "Investor Update Newsletter", f: "Topic → Content" },
    { l: "Market Research Survey", f: "Question → Answer" },
    { l: "Business Case Study", f: "Company → Insight" },
    { l: "Strategic Initiative Tracker", f: "Initiative → Status" },
    { l: "Product Launch Plan", f: "Step → Action" },
    { l: "Business Metrics Dashboard", f: "Metric → Value" },
    { l: "Funding Proposal", f: "Project → Budget" },
    { l: "Sales Pipeline Report", f: "Stage → Lead" },
    { l: "Marketing Budget Plan", f: "Campaign → Cost" },
    { l: "Business Policy Document", f: "Rule → Implementation" },
    { l: "Startup Team Roles", f: "Member → Responsibility" },
    { l: "Customer Journey Map", f: "Stage → Interaction" },
    { l: "Operational Risk Assessment", f: "Risk → Mitigation" },
    { l: "Business Communication Plan", f: "Channel → Message" },
    { l: "Product Feature Prioritization", f: "Feature → Score" },
    { l: "Business Development Notes", f: "Contact → Action" },
    { l: "Strategic Meeting Agenda", f: "Topic → Activity" },
    { l: "Investor Pitch Script", f: "Slide → Talking Point" },
    { l: "Business Expansion Plan", f: "Market → Step" },
    { l: "Competitive Benchmarking Report", f: "Competitor → Metric" },
    { l: "Business Process Improvement Plan", f: "Task → Action" },
    { l: "Revenue Tracking Sheet", f: "Product → Value" },
    { l: "Marketing Content Calendar", f: "Date → Post" },
    { l: "Product Feedback Form", f: "Feature → Rating" },
    { l: "Startup Growth Metrics", f: "Metric → Score" },
    { l: "Operational Efficiency Report", f: "Department → Result" },
    { l: "Business Risk Log", f: "Risk → Resolution" },
    { l: "Team Performance Dashboard", f: "Member → Score" },
    { l: "Financial Statement Template", f: "Account → Value" },
    { l: "Marketing Strategy Notes", f: "Campaign → Observation" },
    { l: "Customer Engagement Plan", f: "Channel → Action" },
    { l: "Sales Strategy Template", f: "Product → Action" },
    { l: "Business Presentation Script", f: "Slide → Content" },
    { l: "Startup Advisory Notes", f: "Topic → Recommendation" },
    { l: "Product Roadmap Updates", f: "Feature → Status" },
    { l: "Business Performance Review", f: "Metric → Evaluation" },
    { l: "Marketing Analytics Report", f: "Metric → Insight" },
    { l: "Investment Term Sheet", f: "Item → Detail" },
    { l: "Revenue Growth Plan", f: "Period → Target" },
    { l: "Operational Guidelines Checklist", f: "Task → Status" },
    { l: "Strategic Plan Summary", f: "Goal → Action" },
    { l: "Product Lifecycle Plan", f: "Stage → Step" },
    { l: "Business Collaboration Plan", f: "Partner → Task" },
    { l: "Sales Team Assignment", f: "Member → Target" },
    { l: "Marketing Proposal Document", f: "Campaign → Goal" },
    { l: "Startup Launch Checklist", f: "Task → Completion" },
    { l: "Business Ethics Policy", f: "Rule → Explanation" },
    { l: "Investor Presentation Notes", f: "Slide → Point" },
    { l: "Market Segmentation Report", f: "Segment → Data" },
    { l: "Business KPI Tracker", f: "Metric → Value" },
    { l: "Product Testing Plan", f: "Feature → Method" },
    { l: "Marketing Campaign Metrics", f: "Channel → Value" },
    { l: "Financial Planning Template", f: "Account → Forecast" },
    { l: "Business Meeting Notes", f: "Topic → Action" },
    { l: "Sales Report Template", f: "Product → Result" },
    { l: "Product Feature Specification", f: "Feature → Detail" },
    { l: "Business Growth Strategy", f: "Initiative → Step" },
    { l: "Startup Risk Assessment", f: "Risk → Mitigation" },
    { l: "Operational Audit Report", f: "Department → Observation" }
];
