
export const CULTURAL_HUMANITIES = [
    { l: "Cultural Research Paper", f: "Topic → Analysis" },
    { l: "Ethnographic Study", f: "Group → Observation" },
    { l: "Historical Event Report", f: "Event → Detail" },
    { l: "Art Critique", f: "Artwork → Evaluation" },
    { l: "Literature Review", f: "Author → Work" },
    { l: "Cultural Heritage Plan", f: "Site → Action" },
    { l: "Museum Exhibit Proposal", f: "Display → Description" },
    { l: "Folklore Study", f: "Story → Analysis" },
    { l: "Anthropology Field Notes", f: "Observation → Date" },
    { l: "Cultural Festival Plan", f: "Event → Schedule" },
    { l: "Comparative Literature Analysis", f: "Work → Theme" },
    { l: "Cultural Policy Document", f: "Rule → Implementation" },
    { l: "Academic Conference Paper", f: "Topic → Result" },
    { l: "Historical Archive Summary", f: "Document → Insight" },
    { l: "Art History Timeline", f: "Artist → Work" },
    { l: "Cultural Survey", f: "Question → Response" },
    { l: "Museum Curation Notes", f: "Object → Display" },
    { l: "Folklore Documentation", f: "Tale → Source" },
    { l: "Cultural Impact Study", f: "Event → Effect" },
    { l: "Historical Biography", f: "Figure → Life" },
    { l: "Comparative Cultural Analysis", f: "Culture → Feature" },
    { l: "Ethnography Report", f: "Group → Finding" },
    { l: "Literature Criticism Notes", f: "Work → Observation" },
    { l: "Museum Exhibition Plan", f: "Theme → Object" },
    { l: "Cultural Resource Inventory", f: "Resource → Description" },
    { l: "Humanities Workshop Agenda", f: "Session → Activity" },
    { l: "Cultural Artifact Catalog", f: "Artifact → Details" },
    { l: "Historical Document Analysis", f: "Document → Insight" },
    { l: "Cultural Trends Report", f: "Topic → Observation" },
    { l: "Literature Class Lesson Plan", f: "Topic → Activity" },
    { l: "Historical Map Annotation", f: "Place → Event" },
    { l: "Cultural Program Proposal", f: "Activity → Budget" },
    { l: "Art Exhibit Review", f: "Piece → Critique" },
    { l: "Comparative Philosophy Paper", f: "Topic → Argument" },
    { l: "Heritage Site Preservation Plan", f: "Site → Action" },
    { l: "Anthropology Lecture Notes", f: "Topic → Detail" },
    { l: "Literature Study Notes", f: "Work → Theme" },
    { l: "Cultural Outreach Plan", f: "Community → Activity" },
    { l: "Museum Tour Guide Script", f: "Exhibit → Info" },
    { l: "Historical Analysis Report", f: "Event → Outcome" },
    { l: "Cultural Interview Notes", f: "Participant → Quote" },
    { l: "Humanities Research Outline", f: "Topic → Sections" },
    { l: "Folklore Interpretation Notes", f: "Tale → Meaning" },
    { l: "Academic Journal Article", f: "Topic → Argument" },
    { l: "Cultural Blog Post", f: "Topic → Story" },
    { l: "Historical Artifact Description", f: "Artifact → Context" },
    { l: "Comparative Literature Notes", f: "Work → Theme" },
    { l: "Cultural Heritage Inventory", f: "Site → Description" },
    { l: "Museum Event Plan", f: "Exhibit → Activity" },
    { l: "Cultural Awareness Workshop", f: "Topic → Session" },
    { l: "Literature Discussion Guide", f: "Work → Questions" },
    { l: "Humanities Project Proposal", f: "Topic → Goal" },
    { l: "Folklore Workshop Plan", f: "Tale → Activity" },
    { l: "Historical Research Memo", f: "Event → Observation" },
    { l: "Cultural Festival Report", f: "Event → Highlights" },
    { l: "Literature Analysis Template", f: "Work → Analysis" },
    { l: "Art History Research Notes", f: "Artist → Work" },
    { l: "Cultural Policy Analysis", f: "Rule → Impact" },
    { l: "Museum Exhibit Feedback", f: "Visitor → Response" },
    { l: "Anthropology Research Memo", f: "Group → Notes" },
    { l: "Historical Archive Digitization Plan", f: "Document → Step" },
    { l: "Cultural Program Evaluation", f: "Initiative → Outcome" },
    { l: "Literature Curriculum Plan", f: "Topic → Lessons" },
    { l: "Folklore Recording Log", f: "Story → Source" },
    { l: "Humanities Grant Proposal", f: "Project → Budget" }
];
