
export const EDUCATION_TEACHING = [
    { l: "Curriculum Development Plan", f: "Subject → Lesson" },
    { l: "Lesson Plan Template", f: "Topic → Activity" },
    { l: "Educational Workshop Agenda", f: "Session → Activity" },
    { l: "Student Progress Tracker", f: "Student → Metric" },
    { l: "Online Course Module", f: "Topic → Content" },
    { l: "Teacher Evaluation Form", f: "Teacher → Metric" },
    { l: "Assessment Blueprint", f: "Test → Section" },
    { l: "Learning Outcome Report", f: "Objective → Result" },
    { l: "Classroom Activity Guide", f: "Topic → Step" },
    { l: "Study Guide", f: "Topic → Key Points" },
    { l: "Educational Blog Post", f: "Topic → Article" },
    { l: "Lesson Observation Notes", f: "Class → Observation" },
    { l: "Educational Research Proposal", f: "Hypothesis → Method" },
    { l: "Learning Analytics Dashboard", f: "Metric → Value" },
    { l: "Curriculum Mapping Document", f: "Topic → Outcome" },
    { l: "Student Feedback Form", f: "Question → Response" },
    { l: "Teaching Resource List", f: "Resource → Usage" },
    { l: "Online Learning Content Plan", f: "Module → Step" },
    { l: "Classroom Management Plan", f: "Strategy → Procedure" },
    { l: "Learning Material Template", f: "Topic → Detail" },
    { l: "Teacher Training Plan", f: "Session → Activity" },
    { l: "Educational Policy Document", f: "Rule → Implementation" },
    { l: "Student Portfolio Template", f: "Project → Evidence" },
    { l: "Assessment Rubric", f: "Criterion → Score" },
    { l: "Interactive Lesson Plan", f: "Step → Activity" },
    { l: "Student Engagement Tracker", f: "Metric → Score" },
    { l: "Learning Environment Audit", f: "Classroom → Observation" },
    { l: "Online Course Syllabus", f: "Topic → Lesson" },
    { l: "Educational Video Script", f: "Segment → Instruction" },
    { l: "Lesson Plan Feedback", f: "Topic → Comment" },
    { l: "Education Program Proposal", f: "Initiative → Goal" },
    { l: "Student Mentorship Plan", f: "Student → Activity" },
    { l: "Learning Challenge Plan", f: "Task → Rules" },
    { l: "Educational Workshop Notes", f: "Topic → Activity" },
    { l: "Classroom Observation Checklist", f: "Task → Status" },
    { l: "Student Achievement Report", f: "Student → Metric" },
    { l: "Learning Resource Evaluation", f: "Resource → Score" },
    { l: "Educational Conference Paper", f: "Topic → Finding" },
    { l: "Learning Module Design", f: "Topic → Step" },
    { l: "Teaching Strategy Notes", f: "Topic → Observation" },
    { l: "Assessment Analysis", f: "Test → Result" },
    { l: "Student Behavior Report", f: "Student → Observation" },
    { l: "Curriculum Update Proposal", f: "Subject → Change" },
    { l: "E-Learning Activity Plan", f: "Task → Duration" },
    { l: "Teacher Handbook", f: "Topic → Instruction" },
    { l: "Student Survey", f: "Question → Response" },
    { l: "Lesson Plan Archive", f: "Topic → Version" },
    { l: "Classroom Technology Guide", f: "Tool → Usage" },
    { l: "Peer Teaching Plan", f: "Student → Activity" },
    { l: "Learning Innovation Report", f: "Initiative → Outcome" },
    { l: "Student Goal Setting Sheet", f: "Goal → Deadline" },
    { l: "Teaching Evaluation Notes", f: "Topic → Observation" },
    { l: "Educational Grant Proposal", f: "Project → Budget" },
    { l: "Classroom Project Timeline", f: "Task → Completion" },
    { l: "Learning Outcome Dashboard", f: "Objective → Score" },
    { l: "Student Reflection Worksheet", f: "Topic → Response" },
    { l: "Teacher Workshop Feedback", f: "Session → Comment" },
    { l: "Online Course Evaluation", f: "Module → Feedback" },
    { l: "Classroom Design Plan", f: "Space → Arrangement" },
    { l: "Educational Newsletter", f: "Topic → Article" },
    { l: "Lesson Plan Revision Notes", f: "Topic → Adjustment" },
    { l: "Student Achievement Tracker", f: "Metric → Value" },
    { l: "E-Learning Module Notes", f: "Topic → Step" },
    { l: "Learning Strategy Memo", f: "Topic → Action" },
    { l: "Educational Technology Implementation Plan", f: "Tool → Step" }
];
