
export const ENTERTAINMENT_MEDIA = [
    { l: "Movie Script", f: "Scene → Dialogue" },
    { l: "TV Show Episode Outline", f: "Act → Scene" },
    { l: "Film Treatment", f: "Concept → Plot" },
    { l: "Casting Call Sheet", f: "Role → Requirements" },
    { l: "Storyboard Panel", f: "Shot → Description" },
    { l: "Music Album Plan", f: "Track → Details" },
    { l: "Song Lyrics Draft", f: "Verse → Line" },
    { l: "Podcast Episode Plan", f: "Segment → Topic" },
    { l: "Video Production Schedule", f: "Scene → Time" },
    { l: "Press Release", f: "Event → Message" },
    { l: "Entertainment Blog Post", f: "Topic → Review" },
    { l: "Media Coverage Report", f: "Event → Summary" },
    { l: "Film Budget", f: "Department → Cost" },
    { l: "TV Show Shooting Schedule", f: "Episode → Scene" },
    { l: "Performance Review", f: "Actor → Evaluation" },
    { l: "Set Design Plan", f: "Scene → Props" },
    { l: "Costume Design Sheet", f: "Character → Outfit" },
    { l: "Audio Mixing Notes", f: "Track → Adjustment" },
    { l: "Editing Plan", f: "Scene → Effect" },
    { l: "Script Revision Notes", f: "Scene → Change" },
    { l: "Trailer Outline", f: "Sequence → Visual" },
    { l: "Music Video Concept", f: "Scene → Action" },
    { l: "Casting Summary", f: "Actor → Role" },
    { l: "Audience Feedback Form", f: "Question → Response" },
    { l: "Streaming Platform Proposal", f: "Show → Schedule" },
    { l: "Film Festival Submission", f: "Entry → Details" },
    { l: "Soundtrack List", f: "Track → Duration" },
    { l: "Media Campaign Plan", f: "Channel → Action" },
    { l: "Entertainment Event Agenda", f: "Time → Activity" },
    { l: "Behind the Scenes Report", f: "Task → Observation" },
    { l: "Actor Interview Notes", f: "Question → Answer" },
    { l: "Scene Blocking Diagram", f: "Actor → Position" },
    { l: "Showrunner Notes", f: "Episode → Direction" },
    { l: "Promotional Video Script", f: "Segment → Dialogue" },
    { l: "Stage Performance Plan", f: "Act → Cue" },
    { l: "Media Release Calendar", f: "Date → Event" },
    { l: "Script Coverage Report", f: "Scene → Analysis" },
    { l: "Production Risk Assessment", f: "Issue → Mitigation" },
    { l: "Video Editing Checklist", f: "Task → Status" },
    { l: "Audio Recording Log", f: "Session → Track" },
    { l: "Entertainment Newsletter", f: "Topic → Update" },
    { l: "Story Arc Plan", f: "Episode → Beat" },
    { l: "Media Rights Agreement", f: "Party → Terms" },
    { l: "Voiceover Script", f: "Line → Emotion" },
    { l: "Set Construction Notes", f: "Location → Details" },
    { l: "Music Arrangement Sheet", f: "Track → Instrument" },
    { l: "Digital Content Plan", f: "Platform → Post" },
    { l: "Audience Demographics Report", f: "Segment → Data" },
    { l: "Podcast Show Notes", f: "Episode → Summary" },
    { l: "Event Coverage Plan", f: "Media → Schedule" },
    { l: "Post-Production Timeline", f: "Task → Deadline" },
    { l: "Actor Performance Notes", f: "Scene → Observation" },
    { l: "Content Review Checklist", f: "Item → Status" },
    { l: "Casting Call Application", f: "Actor → Info" },
    { l: "Entertainment Analytics Report", f: "Metric → Insight" },
    { l: "Creative Brief", f: "Project → Objective" },
    { l: "Film Concept Art", f: "Scene → Sketch" },
    { l: "Script Continuity Notes", f: "Scene → Change" },
    { l: "Music Collaboration Proposal", f: "Artist → Track" },
    { l: "Episode Recap", f: "Scene → Summary" },
    { l: "Show Concept Pitch", f: "Idea → Benefit" },
    { l: "Media Sponsorship Proposal", f: "Brand → Exposure" },
    { l: "Audience Engagement Plan", f: "Activity → Measurement" },
    { l: "Entertainment Industry Research", f: "Topic → Finding" },
    { l: "Film Festival Review", f: "Movie → Score" }
];
