
export const ENVIRONMENTAL_SUSTAINABILITY = [
    { l: "Renewable Energy Project Plan", f: "Source → Output" },
    { l: "Environmental Impact Study", f: "Project → Result" },
    { l: "Carbon Footprint Report", f: "Activity → Emission" },
    { l: "Sustainability Proposal", f: "Initiative → Steps" },
    { l: "Water Conservation Plan", f: "Area → Method" },
    { l: "Wildlife Protection Plan", f: "Species → Action" },
    { l: "Habitat Restoration Notes", f: "Area → Procedure" },
    { l: "Pollution Monitoring Report", f: "Source → Level" },
    { l: "Eco-Friendly Product Plan", f: "Item → Material" },
    { l: "Climate Change Adaptation Plan", f: "Risk → Strategy" },
    { l: "Environmental Grant Proposal", f: "Project → Budget" },
    { l: "Green Building Certification", f: "Building → Score" },
    { l: "Environmental Audit", f: "Facility → Compliance" },
    { l: "Waste Management Plan", f: "Waste Type → Disposal" },
    { l: "Energy Efficiency Assessment", f: "System → Recommendation" },
    { l: "Sustainable Agriculture Plan", f: "Crop → Method" },
    { l: "Environmental Education Program", f: "Topic → Activity" },
    { l: "Recycling Program Guidelines", f: "Material → Instruction" },
    { l: "Urban Green Space Plan", f: "Area → Feature" },
    { l: "Environmental Risk Assessment", f: "Hazard → Mitigation" },
    { l: "Air Quality Monitoring Report", f: "Location → Values" },
    { l: "Water Quality Testing Report", f: "Source → Result" },
    { l: "Environmental Project Timeline", f: "Task → Deadline" },
    { l: "Coastal Protection Plan", f: "Shore → Measure" },
    { l: "Ecological Survey", f: "Species → Count" },
    { l: "Environmental Policy Document", f: "Rule → Implementation" },
    { l: "Forest Conservation Plan", f: "Area → Method" },
    { l: "Renewable Energy Feasibility Study", f: "Site → Output" },
    { l: "Wildlife Monitoring Log", f: "Species → Observation" },
    { l: "Eco-Tourism Development Plan", f: "Site → Activities" },
    { l: "Energy Consumption Analysis", f: "Device → Metric" },
    { l: "Climate Policy Review", f: "Measure → Outcome" },
    { l: "Natural Resource Management Plan", f: "Resource → Action" },
    { l: "Soil Conservation Plan", f: "Field → Measure" },
    { l: "Flood Risk Assessment", f: "Zone → Probability" },
    { l: "Environmental Awareness Campaign", f: "Topic → Audience" },
    { l: "Hazardous Waste Report", f: "Type → Quantity" },
    { l: "Sustainable Transport Plan", f: "Mode → Efficiency" },
    { l: "Renewable Energy Implementation Notes", f: "Source → Action" },
    { l: "Environmental Compliance Checklist", f: "Task → Status" },
    { l: "Wildlife Rehabilitation Plan", f: "Species → Care" },
    { l: "Carbon Reduction Strategy", f: "Activity → Savings" },
    { l: "Environmental Research Proposal", f: "Hypothesis → Method" },
    { l: "Energy Audit Report", f: "System → Findings" },
    { l: "Environmental Project Evaluation", f: "Initiative → Result" },
    { l: "Ecosystem Restoration Timeline", f: "Task → Completion" },
    { l: "Climate Resilience Report", f: "Region → Measures" },
    { l: "Green Product Development Plan", f: "Material → Step" },
    { l: "Sustainability Metrics Dashboard", f: "Indicator → Value" },
    { l: "Environmental Data Analysis", f: "Dataset → Insight" },
    { l: "Natural Disaster Preparedness Plan", f: "Hazard → Response" },
    { l: "Eco-Friendly Packaging Guide", f: "Material → Instruction" },
    { l: "Waste Reduction Strategy", f: "Method → Target" },
    { l: "Environmental Program Report", f: "Activity → Outcome" },
    { l: "Water Conservation Campaign", f: "Area → Action" },
    { l: "Renewable Energy Policy Proposal", f: "Initiative → Goal" },
    { l: "Ecological Footprint Assessment", f: "Activity → Impact" },
    { l: "Community Sustainability Workshop", f: "Topic → Session" },
    { l: "Biodiversity Inventory", f: "Area → Species" },
    { l: "Carbon Accounting Report", f: "Activity → Emission" },
    { l: "Environmental Impact Memo", f: "Issue → Recommendation" },
    { l: "Resource Efficiency Plan", f: "Area → Saving" },
    { l: "Sustainable Development Goals Progress", f: "Indicator → Score" },
    { l: "Environmental Conference Agenda", f: "Topic → Speaker" },
    { l: "Renewable Energy Tracking Sheet", f: "Device → Output" },
    { l: "Green Building Maintenance Checklist", f: "Task → Status" },
    { l: "Environmental Project Log", f: "Date → Activity" },
    { l: "Environmental Newsletter", f: "Topic → Article" },
    { l: "Climate Change Awareness Material", f: "Topic → Action" },
    { l: "Eco-Friendly Product Evaluation", f: "Product → Score" }
];
