
export const GAMING_ESPORTS = [
    { l: "Game Design Document", f: "Feature → Detail" },
    { l: "Level Design Plan", f: "Level → Objective" },
    { l: "Character Profile", f: "Name → Ability" },
    { l: "Game Mechanics Outline", f: "Action → Rule" },
    { l: "Match Schedule", f: "Player → Time" },
    { l: "Tournament Bracket", f: "Team → Round" },
    { l: "Player Stats Sheet", f: "Player → Score" },
    { l: "Strategy Guide", f: "Map → Tip" },
    { l: "Game Development Timeline", f: "Phase → Task" },
    { l: "Patch Notes", f: "Version → Change" },
    { l: "Game Review", f: "Feature → Rating" },
    { l: "Esports Event Plan", f: "Match → Time" },
    { l: "Player Training Plan", f: "Skill → Exercise" },
    { l: "Leaderboard Report", f: "Player → Rank" },
    { l: "Tournament Rules", f: "Rule → Detail" },
    { l: "Match Recap", f: "Player → Action" },
    { l: "Game Concept Pitch", f: "Idea → Feature" },
    { l: "Game Testing Checklist", f: "Task → Status" },
    { l: "Game Storyboard", f: "Scene → Action" },
    { l: "Bug Tracking Sheet", f: "Bug → Status" },
    { l: "Game Analytics Report", f: "Metric → Value" },
    { l: "Strategy Session Notes", f: "Topic → Tactic" },
    { l: "Character Ability Balancing", f: "Character → Value" },
    { l: "Player Evaluation", f: "Player → Skill Rating" },
    { l: "Game Level Flowchart", f: "Level → Step" },
    { l: "Tournament Results", f: "Match → Winner" },
    { l: "Game Marketing Plan", f: "Campaign → Channel" },
    { l: "Esports Team Roster", f: "Player → Role" },
    { l: "Game Development Notes", f: "Feature → Observation" },
    { l: "Patch Testing Log", f: "Bug → Status" },
    { l: "Game Mechanics Documentation", f: "Feature → Rule" },
    { l: "Leaderboard Update", f: "Player → Score" },
    { l: "Streaming Schedule", f: "Platform → Time" },
    { l: "Gameplay Tutorial Script", f: "Step → Instruction" },
    { l: "Game Event Report", f: "Match → Summary" },
    { l: "Player Contract", f: "Player → Terms" },
    { l: "In-Game Economy Plan", f: "Item → Value" },
    { l: "Gaming Workshop Plan", f: "Topic → Activity" },
    { l: "Game Content Outline", f: "Level → Asset" },
    { l: "Beta Testing Feedback", f: "Player → Comment" },
    { l: "Achievement Tracker", f: "Player → Unlock" },
    { l: "Multiplayer Event Plan", f: "Mode → Schedule" },
    { l: "Game Progression Diagram", f: "Level → Next Step" },
    { l: "Esports Strategy Memo", f: "Match → Tactic" },
    { l: "Game Art Design Notes", f: "Asset → Description" },
    { l: "Game Feature Proposal", f: "Idea → Benefit" },
    { l: "Tournament Invitation", f: "Team → Details" },
    { l: "Player Performance Log", f: "Session → Score" },
    { l: "Game Update Schedule", f: "Feature → Date" },
    { l: "Quest Design Document", f: "Quest → Objective" },
    { l: "Competitive Analysis", f: "Game → Strength" },
    { l: "Skill Tree Documentation", f: "Ability → Level" },
    { l: "Game Development Sprint", f: "Task → Deadline" },
    { l: "Player Survey", f: "Question → Answer" },
    { l: "Game Metrics Dashboard", f: "Metric → Value" },
    { l: "Esports Sponsorship Proposal", f: "Brand → Benefit" },
    { l: "Match Replay Analysis", f: "Player → Action" },
    { l: "Game Level Testing Notes", f: "Level → Issue" },
    { l: "Game Feature Testing Plan", f: "Feature → Method" },
    { l: "Narrative Design Plan", f: "Story → Beat" },
    { l: "Player Onboarding Guide", f: "Step → Instruction" },
    { l: "Game Monetization Plan", f: "Feature → Revenue" },
    { l: "Community Engagement Plan", f: "Activity → Target" },
    { l: "Game Patch Rollout Plan", f: "Version → Date" },
    { l: "Bug Fix Summary", f: "Bug → Resolution" },
    { l: "Match Highlight Reel Plan", f: "Clip → Timestamp" },
    { l: "Game User Manual", f: "Feature → Instruction" },
    { l: "Esports Event Report", f: "Match → Winner" },
    { l: "Game Development Retrospective", f: "Sprint → Lesson" },
    { l: "Game Testing Scorecard", f: "Tester → Result" }
];
