
export const HEALTHCARE_MEDICAL = [
    { l: "Patient Intake Form", f: "Personal Info → Medical History" },
    { l: "Medical Report", f: "Diagnosis → Recommendations" },
    { l: "Prescription", f: "Medication → Dosage" },
    { l: "Clinical Trial Protocol", f: "Step → Procedure" },
    { l: "Lab Test Result", f: "Test → Value" },
    { l: "Radiology Report", f: "Scan → Findings" },
    { l: "Surgery Report", f: "Procedure → Outcome" },
    { l: "Discharge Summary", f: "Diagnosis → Advice" },
    { l: "Medication Chart", f: "Drug → Schedule" },
    { l: "Treatment Plan", f: "Condition → Steps" },
    { l: "Immunization Record", f: "Vaccine → Date" },
    { l: "Patient Progress Note", f: "Observation → Update" },
    { l: "Case Study", f: "Patient → Treatment Outcome" },
    { l: "Referral Letter", f: "Patient → Specialist" },
    { l: "Medical Consent Form", f: "Procedure → Risks" },
    { l: "Health Assessment", f: "Symptoms → Observations" },
    { l: "Nursing Care Plan", f: "Patient → Tasks" },
    { l: "Vital Signs Record", f: "Time → Measurement" },
    { l: "Lab Requisition", f: "Test → Urgency" },
    { l: "Pathology Report", f: "Sample → Result" },
    { l: "Emergency Report", f: "Incident → Treatment" },
    { l: "Clinical Note", f: "Observation → Recommendation" },
    { l: "Rehabilitation Plan", f: "Therapy → Goal" },
    { l: "Physiotherapy Record", f: "Session → Progress" },
    { l: "Nutrition Plan", f: "Patient → Meal Plan" },
    { l: "Health Survey", f: "Question → Response" },
    { l: "Mental Health Assessment", f: "Symptoms → Score" },
    { l: "Psychotherapy Note", f: "Session → Intervention" },
    { l: "Doctor Consultation Summary", f: "Advice → Next Step" },
    { l: "Patient Education Material", f: "Condition → Guidelines" },
    { l: "Medical Audit", f: "Case → Compliance" },
    { l: "Clinical Guideline", f: "Condition → Procedure" },
    { l: "Health Risk Assessment", f: "Factor → Rating" },
    { l: "Chronic Disease Log", f: "Measurement → Trend" },
    { l: "Diagnostic Flowchart", f: "Symptom → Test" },
    { l: "Appointment Schedule", f: "Patient → Time" },
    { l: "Insurance Claim Form", f: "Policy → Procedure" },
    { l: "Laboratory SOP", f: "Task → Step" },
    { l: "Clinical Trial Report", f: "Participant → Result" },
    { l: "Medical Research Proposal", f: "Hypothesis → Method" },
    { l: "Patient Safety Incident", f: "Event → Action" },
    { l: "Infection Control Plan", f: "Procedure → Compliance" },
    { l: "Hospital Protocol", f: "Department → Instructions" },
    { l: "Triage Note", f: "Patient → Severity" },
    { l: "Medication Administration Record", f: "Patient → Time" },
    { l: "Health Education Pamphlet", f: "Topic → Advice" },
    { l: "Clinical Outcome Report", f: "Case → Result" },
    { l: "Patient Discharge Checklist", f: "Task → Status" },
    { l: "Healthcare Survey", f: "Question → Options" },
    { l: "Telehealth Consultation", f: "Topic → Recommendation" },
    { l: "Vaccination Schedule", f: "Patient → Date" },
    { l: "Lab Safety Checklist", f: "Task → Compliance" },
    { l: "Post-Operative Note", f: "Procedure → Observations" },
    { l: "Medical Billing Statement", f: "Service → Charge" },
    { l: "Nursing Handover", f: "Patient → Update" },
    { l: "Care Plan Evaluation", f: "Goal → Outcome" },
    { l: "Health Improvement Plan", f: "Goal → Action" },
    { l: "Blood Test Log", f: "Date → Result" },
    { l: "Surgical Checklist", f: "Step → Verification" },
    { l: "Anesthesia Record", f: "Drug → Dosage" },
    { l: "Patient Feedback Form", f: "Question → Response" },
    { l: "Medical Coding Sheet", f: "Diagnosis → Code" },
    { l: "Emergency Response Plan", f: "Event → Action" },
    { l: "Health Metrics Dashboard", f: "Indicator → Value" },
    { l: "Clinical KPI Report", f: "Metric → Status" },
    { l: "Patient Flow Chart", f: "Step → Next Step" },
    { l: "Medical Research Notes", f: "Observation → Data" },
    { l: "Case Presentation", f: "History → Findings" },
    { l: "Health Newsletter", f: "Topic → Advice" },
    { l: "Patient Advocacy Document", f: "Issue → Recommendation" },
    { l: "Medical Ethics Report", f: "Issue → Opinion" },
    { l: "Disease Surveillance Report", f: "Data → Trend" },
    { l: "Public Health Advisory", f: "Condition → Guidance" },
    { l: "Pandemic Response Plan", f: "Step → Responsibility" },
    { l: "Hospital Administration Report", f: "Dept → Status" },
    { l: "Clinical Pathway", f: "Step → Outcome" },
    { l: "Medication Error Log", f: "Incident → Action" },
    { l: "Lab Quality Control", f: "Test → Result" },
    { l: "Physiotherapy Progress", f: "Session → Measurement" },
    { l: "Dietary Recommendation", f: "Patient → Meal Plan" },
    { l: "Health Risk Communication", f: "Topic → Action" },
    { l: "Medical Equipment Checklist", f: "Device → Status" },
    { l: "Patient Satisfaction Survey", f: "Question → Feedback" },
    { l: "Clinical Case Discussion", f: "Patient → Analysis" },
    { l: "Health Program Proposal", f: "Goal → Action" }
];
