
export const HEALTH_WELLNESS = [
    { l: "Patient Intake Form", f: "Personal Info → History" },
    { l: "Medical Treatment Plan", f: "Condition → Therapy" },
    { l: "Wellness Program Proposal", f: "Initiative → Steps" },
    { l: "Fitness Tracking Log", f: "Activity → Metric" },
    { l: "Nutrition Plan", f: "Meal → Calories" },
    { l: "Mental Health Assessment", f: "Patient → Score" },
    { l: "Therapy Session Notes", f: "Client → Observation" },
    { l: "Health Survey", f: "Question → Answer" },
    { l: "Exercise Routine Sheet", f: "Exercise → Reps" },
    { l: "Health Risk Assessment", f: "Factor → Severity" },
    { l: "Medication Schedule", f: "Drug → Dose" },
    { l: "Clinical Trial Protocol", f: "Task → Step" },
    { l: "Patient Progress Report", f: "Date → Metric" },
    { l: "Wellness Workshop Agenda", f: "Topic → Activity" },
    { l: "Nutrition Guidelines", f: "Meal → Nutrient" },
    { l: "Fitness Program Timeline", f: "Task → Completion" },
    { l: "Therapy Goal Setting Sheet", f: "Goal → Target" },
    { l: "Health Newsletter", f: "Topic → Article" },
    { l: "Medical Research Notes", f: "Observation → Data" },
    { l: "Patient Feedback Form", f: "Question → Response" },
    { l: "Exercise Plan Template", f: "Exercise → Step" },
    { l: "Wellness Campaign Plan", f: "Activity → Channel" },
    { l: "Clinical Observation Log", f: "Patient → Note" },
    { l: "Diet Tracking Sheet", f: "Meal → Metric" },
    { l: "Health Policy Document", f: "Rule → Implementation" },
    { l: "Therapy Evaluation Form", f: "Session → Feedback" },
    { l: "Patient Education Material", f: "Topic → Content" },
    { l: "Exercise Program Feedback", f: "Participant → Comment" },
    { l: "Nutrition Analysis Report", f: "Meal → Value" },
    { l: "Wellness Resource List", f: "Item → Usage" },
    { l: "Mental Health Workshop Plan", f: "Topic → Activity" },
    { l: "Fitness Challenge Plan", f: "Task → Rules" },
    { l: "Medical Research Proposal", f: "Hypothesis → Method" },
    { l: "Health Metrics Dashboard", f: "Metric → Value" },
    { l: "Patient Support Plan", f: "Issue → Action" },
    { l: "Wellness Program Evaluation", f: "Initiative → Result" },
    { l: "Therapy Homework Assignment", f: "Task → Instruction" },
    { l: "Clinical Trial Results", f: "Patient → Outcome" },
    { l: "Exercise Attendance Sheet", f: "Participant → Status" },
    { l: "Health Improvement Plan", f: "Goal → Steps" },
    { l: "Nutrition Workshop Plan", f: "Topic → Activity" },
    { l: "Therapy Progress Tracker", f: "Session → Notes" },
    { l: "Patient Goal Setting Sheet", f: "Goal → Deadline" },
    { l: "Health Education Curriculum", f: "Topic → Lesson" },
    { l: "Wellness Blog Post", f: "Topic → Story" },
    { l: "Exercise Routine Adjustment Notes", f: "Exercise → Change" },
    { l: "Medical Case Study", f: "Patient → Analysis" },
    { l: "Mental Health Program Proposal", f: "Initiative → Budget" },
    { l: "Fitness Metrics Tracker", f: "Participant → Metric" },
    { l: "Therapy Session Agenda", f: "Topic → Step" },
    { l: "Nutrition Program Timeline", f: "Meal → Step" },
    { l: "Health Compliance Checklist", f: "Task → Status" },
    { l: "Exercise Safety Guidelines", f: "Activity → Precaution" },
    { l: "Wellness Feedback Form", f: "Question → Answer" },
    { l: "Patient Record Summary", f: "Patient → Condition" },
    { l: "Therapy Resource Material", f: "Topic → Content" },
    { l: "Fitness Assessment Form", f: "Participant → Score" },
    { l: "Nutrition Plan Revision Notes", f: "Meal → Change" },
    { l: "Health Event Proposal", f: "Topic → Schedule" },
    { l: "Clinical Trial Observation", f: "Task → Result" },
    { l: "Wellness Program Tracker", f: "Activity → Completion" },
    { l: "Exercise Log", f: "Participant → Metric" },
    { l: "Patient Risk Mitigation Plan", f: "Issue → Action" },
    { l: "Therapy Evaluation Notes", f: "Session → Observation" },
    { l: "Health Program Impact Report", f: "Initiative → Outcome" },
    { l: "Nutrition Education Plan", f: "Meal → Step" },
    { l: "Fitness Program Guidelines", f: "Exercise → Instruction" },
    { l: "Patient Medication Log", f: "Drug → Dose" },
    { l: "Wellness Workshop Feedback", f: "Participant → Comment" },
    { l: "Therapy Timeline", f: "Session → Action" }
];
