
export const HISTORICAL_RESEARCH = [
    { l: "Timeline of Events", f: "Year → Event" },
    { l: "Historical Figure Profile", f: "Name → Contribution" },
    { l: "Archive Research Notes", f: "Document → Summary" },
    { l: "Primary Source Analysis", f: "Source → Insight" },
    { l: "Historical Map Annotation", f: "Location → Detail" },
    { l: "Event Chronology", f: "Event → Date" },
    { l: "Research Paper Outline", f: "Section → Content" },
    { l: "Historical Artifact Record", f: "Artifact → Description" },
    { l: "Document Transcription Notes", f: "Document → Text" },
    { l: "Comparative Analysis Sheet", f: "Era → Observation" },
    { l: "Historical Workshop Agenda", f: "Topic → Activity" },
    { l: "Archive Inventory", f: "Item → Location" },
    { l: "Historical Case Study", f: "Event → Impact" },
    { l: "Research Proposal Template", f: "Topic → Method" },
    { l: "Historical Event Summary", f: "Event → Outcome" },
    { l: "Timeline Revision Notes", f: "Year → Change" },
    { l: "Biography Notes", f: "Person → Detail" },
    { l: "Research Reference Sheet", f: "Source → Citation" },
    { l: "Historical Context Notes", f: "Event → Background" },
    { l: "Primary Document Checklist", f: "Item → Status" },
    { l: "Archival Research Plan", f: "Archive → Step" },
    { l: "Historical Comparison Table", f: "Event → Metric" },
    { l: "Historical Research Log", f: "Task → Observation" },
    { l: "Artifact Provenance Sheet", f: "Artifact → Origin" },
    { l: "Historical Thesis Outline", f: "Section → Argument" },
    { l: "Archive Catalog Template", f: "Document → Classification" },
    { l: "Event Analysis Notes", f: "Event → Observation" },
    { l: "Historical Workshop Materials", f: "Item → Usage" },
    { l: "Research Methodology Notes", f: "Topic → Detail" },
    { l: "Historical Timeline Dashboard", f: "Event → Date" },
    { l: "Archive Document Summary", f: "Document → Insight" },
    { l: "Comparative Historical Study", f: "Event → Finding" },
    { l: "Biography Draft", f: "Person → Story" },
    { l: "Archive Research Checklist", f: "Task → Status" },
    { l: "Historical Figures Relationship Map", f: "Person → Connection" },
    { l: "Document Translation Notes", f: "Document → Text" },
    { l: "Historical Event Tracker", f: "Event → Status" },
    { l: "Research Notes Archive", f: "Topic → Detail" },
    { l: "Primary Source Index", f: "Source → Page" },
    { l: "Historical Site Report", f: "Site → Observation" },
    { l: "Research Proposal Notes", f: "Topic → Plan" },
    { l: "Artifact Cataloging Template", f: "Artifact → Detail" },
    { l: "Historical Analysis Table", f: "Event → Metric" },
    { l: "Archival Digitization Plan", f: "Document → Step" },
    { l: "Event Context Notes", f: "Event → Background" },
    { l: "Historical Research Presentation", f: "Topic → Slide" },
    { l: "Archive Conservation Plan", f: "Item → Procedure" },
    { l: "Historical Document Review", f: "Document → Comment" },
    { l: "Research Progress Tracker", f: "Task → Status" },
    { l: "Historical Interpretation Notes", f: "Event → Insight" },
    { l: "Archive Metadata Sheet", f: "Document → Field" },
    { l: "Timeline Draft", f: "Event → Date" },
    { l: "Historical Debate Notes", f: "Topic → Argument" },
    { l: "Research Bibliography", f: "Source → Citation" },
    { l: "Archive Access Log", f: "Document → User" },
    { l: "Historical Data Visualization Plan", f: "Metric → Chart" },
    { l: "Comparative Artifact Analysis", f: "Artifact → Detail" },
    { l: "Research Paper Draft", f: "Section → Paragraph" },
    { l: "Event Impact Assessment", f: "Event → Outcome" },
    { l: "Historical Reference Guide", f: "Topic → Detail" },
    { l: "Archival Research Timeline", f: "Task → Date" },
    { l: "Historical Workshop Feedback", f: "Participant → Comment" },
    { l: "Document Authentication Notes", f: "Document → Verification" },
    { l: "Research Observation Template", f: "Task → Note" },
    { l: "Historical Research Dashboard", f: "Metric → Value" }
];
