
export const LEGAL_COMPLIANCE = [
    { l: "Contract Template", f: "Clause → Detail" },
    { l: "Compliance Checklist", f: "Task → Status" },
    { l: "Legal Opinion", f: "Issue → Recommendation" },
    { l: "Regulatory Report", f: "Regulation → Compliance" },
    { l: "Terms & Conditions Draft", f: "Section → Clause" },
    { l: "Intellectual Property Agreement", f: "Party → Rights" },
    { l: "Risk Management Policy", f: "Risk → Procedure" },
    { l: "Case Study Analysis", f: "Case → Outcome" },
    { l: "Legal Memorandum", f: "Topic → Analysis" },
    { l: "Employment Contract Template", f: "Role → Clause" },
    { l: "Data Protection Policy", f: "Rule → Implementation" },
    { l: "Non-Disclosure Agreement", f: "Party → Clause" },
    { l: "Legal Compliance Audit", f: "Task → Status" },
    { l: "Corporate Governance Guidelines", f: "Policy → Detail" },
    { l: "Legal Research Notes", f: "Case → Observation" },
    { l: "Contract Review Checklist", f: "Clause → Status" },
    { l: "Policy Implementation Plan", f: "Policy → Step" },
    { l: "Regulatory Update Memo", f: "Regulation → Summary" },
    { l: "Risk Assessment Report", f: "Risk → Level" },
    { l: "Licensing Agreement Template", f: "Licensee → Rights" },
    { l: "Legal Case Timeline", f: "Event → Date" },
    { l: "Compliance Training Agenda", f: "Topic → Session" },
    { l: "Legal Document Review Notes", f: "Document → Comment" },
    { l: "Intellectual Property Filing", f: "Asset → Action" },
    { l: "Legal Audit Report", f: "Department → Finding" },
    { l: "Contract Negotiation Notes", f: "Clause → Discussion" },
    { l: "Regulatory Compliance Tracker", f: "Regulation → Status" },
    { l: "Legal Brief Template", f: "Topic → Argument" },
    { l: "Litigation Case Notes", f: "Case → Action" },
    { l: "Legal Risk Mitigation Plan", f: "Risk → Strategy" },
    { l: "Policy Review Notes", f: "Policy → Comment" },
    { l: "Compliance Program Evaluation", f: "Initiative → Result" },
    { l: "Employment Law Summary", f: "Rule → Application" },
    { l: "Contract Drafting Notes", f: "Clause → Revision" },
    { l: "Regulatory Filing Checklist", f: "Document → Status" },
    { l: "Legal Workshop Agenda", f: "Topic → Activity" },
    { l: "Litigation Strategy Plan", f: "Case → Step" },
    { l: "Legal Policy Dashboard", f: "Metric → Value" },
    { l: "Compliance Risk Log", f: "Issue → Resolution" },
    { l: "Corporate Legal Guidelines", f: "Topic → Instruction" },
    { l: "Intellectual Property Strategy", f: "Asset → Action" },
    { l: "Contract Signing Tracker", f: "Contract → Date" },
    { l: "Legal Document Template", f: "Type → Section" },
    { l: "Regulatory Compliance Memo", f: "Rule → Summary" },
    { l: "Legal Research Proposal", f: "Topic → Method" },
    { l: "Case Law Analysis", f: "Case → Insight" },
    { l: "Contract Amendment Log", f: "Clause → Change" },
    { l: "Policy Implementation Notes", f: "Task → Status" },
    { l: "Compliance Workshop Plan", f: "Topic → Activity" },
    { l: "Legal Opinion Draft", f: "Topic → Recommendation" },
    { l: "Employment Compliance Checklist", f: "Task → Status" },
    { l: "Litigation Timeline", f: "Case → Milestone" },
    { l: "Contract Management Dashboard", f: "Contract → Status" },
    { l: "Legal Risk Assessment Matrix", f: "Risk → Score" },
    { l: "Regulatory Filing Timeline", f: "Document → Date" },
    { l: "Policy Communication Plan", f: "Audience → Method" },
    { l: "Compliance Monitoring Report", f: "Task → Result" },
    { l: "Intellectual Property Audit", f: "Asset → Finding" },
    { l: "Legal Meeting Notes", f: "Topic → Action" },
    { l: "Contract Termination Plan", f: "Clause → Step" },
    { l: "Regulatory Compliance Guidelines", f: "Rule → Instruction" },
    { l: "Legal Case File Summary", f: "Case → Detail" },
    { l: "Policy Update Memo", f: "Policy → Summary" },
    { l: "Compliance Feedback Form", f: "Question → Response" },
    { l: "Legal Document Archive", f: "Document → Index" }
];
