
export const MEDIA_JOURNALISM = [
    { l: "News Article Template", f: "Headline → Body" },
    { l: "Editorial Plan", f: "Topic → Angle" },
    { l: "Press Release", f: "Event → Detail" },
    { l: "Feature Story Outline", f: "Section → Content" },
    { l: "Interview Questions", f: "Person → Question" },
    { l: "Media Coverage Report", f: "Outlet → Story" },
    { l: "Social Media Post Plan", f: "Platform → Message" },
    { l: "Broadcast Script", f: "Segment → Dialogue" },
    { l: "Podcast Episode Plan", f: "Topic → Segment" },
    { l: "Journalism Ethics Checklist", f: "Task → Status" },
    { l: "Newsroom Assignment Sheet", f: "Reporter → Task" },
    { l: "Media Monitoring Report", f: "Source → Coverage" },
    { l: "Column Outline", f: "Topic → Paragraph" },
    { l: "Press Kit Content", f: "Item → Description" },
    { l: "Investigative Report Notes", f: "Case → Finding" },
    { l: "Editorial Calendar", f: "Date → Article" },
    { l: "Media Event Plan", f: "Activity → Step" },
    { l: "Photography Shot List", f: "Scene → Description" },
    { l: "Video Production Script", f: "Scene → Shot" },
    { l: "Journalist Research Notes", f: "Topic → Source" },
    { l: "Media Release Timeline", f: "Task → Date" },
    { l: "Story Pitch Template", f: "Idea → Angle" },
    { l: "Feature Article Draft", f: "Section → Paragraph" },
    { l: "Social Media Metrics Report", f: "Metric → Value" },
    { l: "Editorial Feedback Form", f: "Article → Comment" },
    { l: "Interview Transcript", f: "Question → Answer" },
    { l: "News Segment Rundown", f: "Segment → Time" },
    { l: "Media Campaign Plan", f: "Channel → Goal" },
    { l: "Video Storyboard Template", f: "Scene → Frame" },
    { l: "Podcast Script Notes", f: "Segment → Talking Point" },
    { l: "Journalism Workshop Agenda", f: "Topic → Activity" },
    { l: "News Analysis Report", f: "Topic → Insight" },
    { l: "Press Release Checklist", f: "Item → Status" },
    { l: "Editorial Guidelines", f: "Section → Instruction" },
    { l: "Media Coverage Map", f: "Location → Story" },
    { l: "Story Research Plan", f: "Topic → Source" },
    { l: "Column Draft Template", f: "Topic → Paragraph" },
    { l: "Video Editing Timeline", f: "Scene → Duration" },
    { l: "Podcast Episode Outline", f: "Segment → Script" },
    { l: "Journalism Ethics Memo", f: "Topic → Recommendation" },
    { l: "News Brief Template", f: "Headline → Summary" },
    { l: "Interview Preparation Notes", f: "Person → Question" },
    { l: "Media Strategy Dashboard", f: "Metric → Value" },
    { l: "Press Conference Plan", f: "Topic → Step" },
    { l: "Editorial Meeting Notes", f: "Topic → Action" },
    { l: "Journalism Pitch Deck", f: "Slide → Content" },
    { l: "Newsroom Workflow Chart", f: "Task → Next Step" },
    { l: "Feature Story Timeline", f: "Section → Completion" },
    { l: "Social Media Content Calendar", f: "Date → Post" },
    { l: "Photography Shoot Plan", f: "Location → Shot" },
    { l: "Video Production Notes", f: "Scene → Detail" },
    { l: "Podcast Production Timeline", f: "Segment → Date" },
    { l: "Media Evaluation Form", f: "Story → Score" },
    { l: "Investigative Notes Archive", f: "Case → Observation" },
    { l: "Press Coverage Analysis", f: "Outlet → Result" },
    { l: "Editorial Revision Log", f: "Article → Change" },
    { l: "Storyboard Template", f: "Scene → Action" },
    { l: "Media Collaboration Plan", f: "Partner → Task" },
    { l: "Newsroom Editorial Dashboard", f: "Metric → Value" },
    { l: "Video Script Revision Notes", f: "Scene → Adjustment" },
    { l: "Podcast Episode Feedback", f: "Segment → Comment" },
    { l: "Journalism Training Material", f: "Topic → Module" },
    { l: "News Alert Template", f: "Headline → Detail" },
    { l: "Feature Article Research Notes", f: "Section → Source" },
    { l: "Social Media Engagement Tracker", f: "Platform → Metric" },
    { l: "Media Ethics Policy", f: "Rule → Instruction" },
    { l: "Press Release Archive", f: "Event → Date" },
    { l: "Column Feedback Form", f: "Paragraph → Comment" },
    { l: "Journalism Grant Proposal", f: "Project → Budget" },
    { l: "Media Event Evaluation", f: "Activity → Outcome" }
];
