
export const SPORTS_RECREATION = [
    { l: "Training Schedule", f: "Athlete → Session" },
    { l: "Game Plan Template", f: "Match → Strategy" },
    { l: "Team Roster", f: "Player → Position" },
    { l: "Fitness Assessment", f: "Player → Score" },
    { l: "Sports Event Proposal", f: "Activity → Step" },
    { l: "Match Analysis Report", f: "Team → Result" },
    { l: "Player Performance Log", f: "Athlete → Metric" },
    { l: "Coaching Notes", f: "Player → Instruction" },
    { l: "Tournament Bracket Template", f: "Team → Match" },
    { l: "Sports Injury Report", f: "Player → Observation" },
    { l: "Practice Drill Plan", f: "Drill → Duration" },
    { l: "Athlete Progress Tracker", f: "Athlete → Metric" },
    { l: "Sports Psychology Notes", f: "Player → Observation" },
    { l: "Event Timeline", f: "Activity → Date" },
    { l: "Fitness Program Plan", f: "Exercise → Step" },
    { l: "Team Strategy Notes", f: "Player → Tactic" },
    { l: "Sports Metrics Dashboard", f: "Metric → Value" },
    { l: "Game Recap Notes", f: "Team → Summary" },
    { l: "Coaching Session Agenda", f: "Topic → Activity" },
    { l: "Player Feedback Form", f: "Question → Response" },
    { l: "Sports Nutrition Plan", f: "Meal → Calories" },
    { l: "Training Attendance Sheet", f: "Player → Status" },
    { l: "Match Highlights Script", f: "Segment → Content" },
    { l: "Athlete Goal Setting Sheet", f: "Goal → Deadline" },
    { l: "Sports Policy Document", f: "Rule → Instruction" },
    { l: "Tournament Planning Notes", f: "Task → Assignment" },
    { l: "Player Evaluation Form", f: "Player → Score" },
    { l: "Team Meeting Notes", f: "Topic → Action" },
    { l: "Exercise Drill Revision Notes", f: "Drill → Change" },
    { l: "Sports Video Script", f: "Scene → Shot" },
    { l: "Tournament Schedule", f: "Match → Date" },
    { l: "Athletic Workshop Agenda", f: "Session → Activity" },
    { l: "Player Medical History", f: "Player → Record" },
    { l: "Training Drill Diagram", f: "Drill → Step" },
    { l: "Fitness Metrics Tracker", f: "Athlete → Metric" },
    { l: "Sports Event Budget", f: "Activity → Cost" },
    { l: "Team Performance Report", f: "Metric → Score" },
    { l: "Coaching Plan Template", f: "Session → Step" },
    { l: "Game Film Analysis", f: "Segment → Observation" },
    { l: "Sports Press Release", f: "Event → Detail" },
    { l: "Tournament Logistics Checklist", f: "Task → Status" },
    { l: "Player Recovery Plan", f: "Player → Step" },
    { l: "Fitness Challenge Tracker", f: "Participant → Result" },
    { l: "Game Playbook", f: "Situation → Move" },
    { l: "Team Communication Plan", f: "Channel → Message" },
    { l: "Practice Attendance Tracker", f: "Player → Status" },
    { l: "Athlete Feedback Log", f: "Player → Comment" },
    { l: "Sports Workshop Notes", f: "Topic → Detail" },
    { l: "Player Ranking Sheet", f: "Player → Score" },
    { l: "Match Review Template", f: "Game → Summary" },
    { l: "Sports Sponsorship Proposal", f: "Sponsor → Benefit" },
    { l: "Training Progress Report", f: "Athlete → Result" },
    { l: "Team Formation Diagram", f: "Position → Player" },
    { l: "Sports Grant Proposal", f: "Project → Budget" },
    { l: "Event Coordination Notes", f: "Activity → Task" },
    { l: "Player Skill Assessment", f: "Skill → Score" },
    { l: "Fitness Program Feedback", f: "Participant → Comment" },
    { l: "Sports Media Plan", f: "Channel → Content" },
    { l: "Athlete Injury Recovery Log", f: "Player → Progress" },
    { l: "Training Drill Feedback", f: "Drill → Comment" },
    { l: "Game Strategy Dashboard", f: "Metric → Value" },
    { l: "Sports Ethics Guidelines", f: "Rule → Instruction" },
    { l: "Team Performance Timeline", f: "Task → Completion" },
    { l: "Player Nutrition Log", f: "Player → Meal" },
    { l: "Sports Event Report", f: "Activity → Result" }
];
