
export const TECHNICAL_ENGINEERING = [
    { l: "Technical Specification", f: "Requirements → Constraints" },
    { l: "System Design Doc", f: "Architecture → Flow Diagrams" },
    { l: "API Documentation", f: "Endpoint → Example Requests" },
    { l: "SDK Guide", f: "Feature → Implementation Steps" },
    { l: "Developer Guide", f: "Setup → Usage" },
    { l: "Code Review Summary", f: "Change → Recommendation" },
    { l: "Software Proposal", f: "Overview → Technical Plan" },
    { l: "QA Test Plan", f: "Scenario → Expected Outcome" },
    { l: "Test Case", f: "Steps → Expected Result" },
    { l: "Bug Report", f: "Steps → Expected Behavior" },
    { l: "Change Log", f: "Version → Updates" },
    { l: "Release Notes", f: "Update → Fixes" },
    { l: "Technical Roadmap", f: "Phase → Deliverables" },
    { l: "Cybersecurity Report", f: "Threat → Recommendation" },
    { l: "System Audit", f: "Component → Status" },
    { l: "Network Plan", f: "Topology → Configurations" },
    { l: "Database Schema Doc", f: "Table → Fields" },
    { l: "Algorithm Explanation", f: "Problem → Approach" },
    { l: "Engineering Blueprint Summary", f: "Component → Purpose" },
    { l: "Firmware Manual", f: "Module → Commands" },
    { l: "Hardware Spec", f: "Component → Power Requirements" },
    { l: "Product Requirement Document", f: "Feature → Acceptance Criteria" },
    { l: "UI/UX Spec", f: "Page → Behaviors" },
    { l: "Interaction Flow", f: "Step → Next Step" },
    { l: "Game Design Doc", f: "Mechanic → Gameplay Loop" },
    { l: "Game Level Design", f: "Environment → Objectives" },
    { l: "Software Onboarding", f: "Step → Expected Output" },
    { l: "DevOps Runbook", f: "Incident → Resolution" },
    { l: "CI/CD Guide", f: "Pipeline Step → Tools" },
    { l: "Architecture Decision Record", f: "Context → Decision" },
    { l: "Patch Notes", f: "Issue → Fix" },
    { l: "Error Guide", f: "Code → Explanation" },
    { l: "Debugging Log", f: "Problem → Fix Attempt" },
    { l: "Machine Learning Report", f: "Model → Evaluation" },
    { l: "Dataset Card", f: "Field → Description" },
    { l: "Feature Engineering Doc", f: "Raw Feature → Transformation" },
    { l: "AI Model Card", f: "Architecture → Limitations" },
    { l: "Robotics Report", f: "Component → Function" },
    { l: "IoT Plan", f: "Device → Communication Method" },
    { l: "Cloud Architecture Doc", f: "Service → Configuration" },
    { l: "Virtualization Guide", f: "Machine → Settings" },
    { l: "Containerization Guide", f: "Image → Deployment Steps" },
    { l: "SRE Playbook", f: "Alert → Actions" },
    { l: "Performance Test Report", f: "Metric → Result" },
    { l: "Workflow Diagram", f: "Node → Next Node" },
    { l: "Technical FAQ", f: "Question → Answer" },
    { l: "Build Guide", f: "Step → Tools" },
    { l: "API Changelog", f: "Version → Differences" },
    { l: "Microservice Spec", f: "Service → Endpoints" },
    { l: "Code Migration Plan", f: "Old System → New System" }
];
