
export const TRAVEL_TOURISM = [
    { l: "Travel Itinerary", f: "Day → Activities" },
    { l: "Tour Plan", f: "Location → Schedule" },
    { l: "Hotel Booking", f: "Room → Dates" },
    { l: "Flight Itinerary", f: "Segment → Time" },
    { l: "Travel Guide", f: "City → Attractions" },
    { l: "Tourist Brochure", f: "Location → Highlights" },
    { l: "Travel Budget Plan", f: "Category → Amount" },
    { l: "Visa Application", f: "Applicant → Details" },
    { l: "Travel Insurance Form", f: "Coverage → Duration" },
    { l: "Transportation Schedule", f: "Mode → Timing" },
    { l: "Cruise Plan", f: "Destination → Activities" },
    { l: "Excursion Plan", f: "Site → Duration" },
    { l: "Tour Feedback Form", f: "Question → Response" },
    { l: "Travel Checklist", f: "Item → Status" },
    { l: "Travel Memo", f: "Topic → Recommendation" },
    { l: "Travel Report", f: "Experience → Summary" },
    { l: "Destination Analysis", f: "Feature → Rating" },
    { l: "Cultural Guide", f: "Topic → Explanation" },
    { l: "Hiking Plan", f: "Trail → Difficulty" },
    { l: "Camping Checklist", f: "Item → Quantity" },
    { l: "Travel Photography Plan", f: "Location → Shot" },
    { l: "Travel Blog Post", f: "Topic → Details" },
    { l: "Travel Review", f: "Experience → Rating" },
    { l: "Backpacking Route", f: "Stop → Duration" },
    { l: "Road Trip Plan", f: "Stop → Activity" },
    { l: "Adventure Activity Plan", f: "Task → Safety" },
    { l: "Cruise Itinerary", f: "Port → Schedule" },
    { l: "Event Tourism Proposal", f: "Event → Plan" },
    { l: "Tourist Safety Guidelines", f: "Situation → Response" },
    { l: "Travel Survey", f: "Question → Answer" },
    { l: "Flight Log", f: "Date → Details" },
    { l: "Accommodation Review", f: "Place → Rating" },
    { l: "City Map Annotation", f: "Area → Feature" },
    { l: "Sightseeing Plan", f: "Attraction → Time" },
    { l: "Transportation Ticket", f: "Route → Seat" },
    { l: "Travel Advisory", f: "Location → Warning" },
    { l: "Tourism Statistics Report", f: "Metric → Value" },
    { l: "Destination Marketing Plan", f: "Audience → Campaign" },
    { l: "Travel Promotion", f: "Offer → Period" },
    { l: "Itinerary Summary", f: "Day → Activity" },
    { l: "Local Culture Guide", f: "Topic → Detail" },
    { l: "Travel Experience Journal", f: "Date → Entry" },
    { l: "Tourist Attraction Report", f: "Name → Evaluation" },
    { l: "Travel Agency Proposal", f: "Package → Cost" },
    { l: "Adventure Sports Plan", f: "Activity → Safety Protocol" },
    { l: "Eco-Tourism Plan", f: "Site → Sustainability Measures" },
    { l: "Heritage Site Documentation", f: "Feature → History" },
    { l: "Travel Survey Analysis", f: "Data → Insight" },
    { l: "Travel Risk Assessment", f: "Hazard → Mitigation" },
    { l: "Seasonal Travel Plan", f: "Month → Activities" },
    { l: "Visitor Feedback Summary", f: "Question → Response" },
    { l: "Transportation Policy", f: "Route → Guidelines" },
    { l: "Tourism Campaign Report", f: "Activity → Result" },
    { l: "Destination Promotion Memo", f: "Topic → Action" },
    { l: "Cultural Event Calendar", f: "Event → Date" },
    { l: "Tour Guide Script", f: "Stop → Commentary" },
    { l: "Tourist Emergency Plan", f: "Situation → Procedure" },
    { l: "Travel Packing List", f: "Item → Quantity" },
    { l: "Travel Booking Confirmation", f: "Booking → Details" },
    { l: "Travel Expense Summary", f: "Category → Total" },
    // New additions
    { l: "Destination Overview", f: "Location → Highlight" },
    { l: "Itinerary Template", f: "Day → Activity" },
    { l: "Travel Checklist", f: "Item → Status" },
    { l: "Accommodation Notes", f: "Hotel → Detail" },
    { l: "Transport Plan", f: "Mode → Route" },
    { l: "Travel Budget Planner", f: "Expense → Amount" },
    { l: "Local Attraction Guide", f: "Place → Description" },
    { l: "Cultural Insights Notes", f: "Region → Detail" },
    { l: "Travel Safety Tips", f: "Risk → Precaution" },
    { l: "Travel Journal Template", f: "Date → Entry" },
    { l: "Packing List", f: "Item → Quantity" },
    { l: "Travel Photography Plan", f: "Location → Shot" },
    { l: "Tourist Feedback Form", f: "Question → Answer" },
    { l: "Route Map Annotations", f: "Location → Detail" },
    { l: "Travel Experience Report", f: "Trip → Summary" }
];
