export const BUSINESS_MANAGEMENT = [
    { l: "Business Plan", f: "Executive Summary → Strategy" },
    { l: "Startup Pitch", f: "Problem → Value Proposition" },
    { l: "Product Pitch", f: "Feature → Benefit" },
    { l: "Company Profile", f: "Overview → Services" },
    { l: "SWOT Analysis", f: "Strengths → Weaknesses" },
    { l: "Competitive Analysis", f: "Competitor → Insights" },
    { l: "Market Research", f: "Trend → Forecast" },
    { l: "Feasibility Study", f: "Assessment → Conclusion" },
    { l: "Business Report", f: "Summary → Insights" },
    { l: "Annual Report", f: "Highlights → Performance" },
    { l: "Quarterly Report", f: "Metrics → Analysis" },
    { l: "Financial Statement", f: "Accounts → Totals" },
    { l: "Budget Plan", f: "Category → Allocations" },
    { l: "Profit & Loss Sheet", f: "Revenue → Expense" },
    { l: "Risk Assessment", f: "Hazard → Mitigation" },
    { l: "Compliance Report", f: "Requirement → Status" },
    { l: "Audit Report", f: "Findings → Recommendations" },
    { l: "Strategic Plan", f: "Goal → To-Do Steps" },
    { l: "Operations Manual", f: "Task → Steps" },
    { l: "Standard Operating Procedure", f: "Step → Compliance Notes" },
    { l: "Meeting Agenda", f: "Topic → Time Block" },
    { l: "Meeting Minutes", f: "Discussion → Action Item" },
    { l: "Organizational Chart", f: "Role → Sub-Role" },
    { l: "Employee Handbook", f: "Policy → Rules" },
    { l: "Performance Review", f: "Strength → Improvement" },
    { l: "Hiring Plan", f: "Role → Requirements" },
    { l: "Interview Evaluation", f: "Candidate → Score" },
    { l: "Training Plan", f: "Module → Exercises" },
    { l: "Onboarding Checklist", f: "Step → Requirements" },
    { l: "Sales Report", f: "Product → Metrics" },
    { l: "Sales Pitch", f: "Feature → Benefit" },
    { l: "Marketing Plan", f: "Campaign → Channels" },
    { l: "Campaign Proposal", f: "Objective → Strategy" },
    { l: "Customer Journey Map", f: "Stage → Touchpoint" },
    { l: "CRM Notes", f: "Client → Next Action" },
    { l: "Business Case", f: "Problem → ROI" },
    { l: "Contract", f: "Term → Obligation" },
    { l: "Agreement", f: "Parties → Responsibilities" },
    { l: "Memorandum", f: "Issue → Statement" },
    { l: "Non-disclosure Agreement", f: "Clause → Conditions" },
    { l: "Invoice", f: "Item → Total" },
    { l: "Quotation", f: "Requirement → Estimate" },
    { l: "Purchase Order", f: "Item → Quantity" },
    { l: "Supplier Report", f: "Vendor → Evaluation" },
    { l: "Inventory Report", f: "Item → Stock Level" },
    { l: "Logistics Plan", f: "Route → Schedule" },
    { l: "Shipment Report", f: "Package → Status" },
    { l: "Customer Support Summary", f: "Issue → Resolution" },
    { l: "Call Log", f: "Caller → Summary" },
    { l: "Ticket Report", f: "Issue → Fix" },
    { l: "Partnership Proposal", f: "Synergy → Benefits" },
    { l: "Event Plan", f: "Agenda → Requirements" },
    { l: "Brand Guide", f: "Element → Rules" },
    { l: "Product Requirement", f: "Feature → Behavior" },
    { l: "Value Proposition Canvas", f: "Customer → Benefit" },
    { l: "User Persona", f: "Profile → Needs" },
    { l: "OKR Document", f: "Objective → Key Result" },
    { l: "KPI Report", f: "Metric → Performance" },
    { l: "Risk Log", f: "Issue → Severity" },
    { l: "Governance Document", f: "Rule → Procedure" }
];