export const CREATIVE_MEDIA = [
    { l: "Novel Outline", f: "Chapter → Plot Points" },
    { l: "Story Scene", f: "Setup → Conflict" },
    { l: "Character Profile", f: "Trait → Backstory" },
    { l: "World-building Doc", f: "Region → Culture" },
    { l: "Magic System Doc", f: "Rule → Limit" },
    { l: "Creature Design", f: "Species → Abilities" },
    { l: "Mythology Doc", f: "Origin → Legends" },
    { l: "Short Story", f: "Beginning → Rising Action" },
    { l: "Flash Fiction", f: "Prompt → Twist" },
    { l: "Script", f: "Scene → Dialogue" },
    { l: "Screenplay", f: "Heading → Action" },
    { l: "TV Episode Outline", f: "Act → Beats" },
    { l: "Movie Treatment", f: "Character → Arc" },
    { l: "Comic Script", f: "Panel → Dialogue" },
    { l: "Manga Script", f: "Page → Frame" },
    { l: "Animation Script", f: "Scene → Voice Lines" },
    { l: "Video Script", f: "Segment → Narration" },
    { l: "Documentary Script", f: "Topic → Evidence" },
    { l: "Podcast Script", f: "Section → Conversation" },
    { l: "Audio Drama", f: "Scene → Sound Cues" },
    { l: "Interview Script", f: "Question → Follow-up" },
    { l: "Journalism Article", f: "Lead → Body" },
    { l: "News Story", f: "What → Why" },
    { l: "Opinion Column", f: "Claim → Arguments" },
    { l: "Review", f: "Summary → Critique" },
    { l: "Travel Blog", f: "Location → Experience" },
    { l: "Lifestyle Blog", f: "Topic → Tips" },
    { l: "How-To Article", f: "Step → Example" },
    { l: "Top-10 List", f: "Item → Explanation" },
    { l: "Personal Diary", f: "Day → Thoughts" },
    { l: "Memoir", f: "Memory → Lesson" },
    { l: "Poem", f: "Theme → Imagery" },
    { l: "Lyric Sheet", f: "Verse → Chorus" },
    { l: "Riddle", f: "Clue → Answer" },
    { l: "Fable", f: "Setup → Moral" },
    { l: "Children's Story", f: "Character → Situation" },
    { l: "Folktale", f: "Myth → Meaning" },
    { l: "Urban Legend", f: "Event → Suspense" },
    { l: "Horror Story", f: "Calm → Rising Dread" },
    { l: "Mystery Story", f: "Clue → Suspect" },
    { l: "Thriller Outline", f: "Tension → Escalation" },
    { l: "Fantasy Outline", f: "Kingdom → Quest" },
    { l: "Sci-Fi Outline", f: "Tech → Conflict" },
    { l: "Romance Outline", f: "Meeting → Tension" },
    { l: "Comedy Script", f: "Setup → Punchline" },
    { l: "Parody Script", f: "Reference → Twist" },
    { l: "Songwriting Plan", f: "Verse → Hook" },
    { l: "Music Album Concept", f: "Track → Emotion" },
    { l: "Speech Script", f: "Opening → Key Points" },
    { l: "Debate Script", f: "Claim → Rebuttal" }
];