
export const CREATIVE_MEDIA = [
    { l: "Novel Outline", f: "Chapter → Plot Points" },
    { l: "Story Scene", f: "Setup → Conflict" },
    { l: "Character Profile", f: "Trait → Backstory" },
    { l: "World-building Doc", f: "Region → Culture" },
    { l: "Magic System Doc", f: "Rule → Limit" },
    { l: "Creature Design", f: "Species → Abilities" },
    { l: "Mythology Doc", f: "Origin → Legends" },
    { l: "Short Story", f: "Beginning → Rising Action" },
    { l: "Flash Fiction", f: "Prompt → Twist" },
    { l: "Script", f: "Scene → Dialogue" },
    { l: "Screenplay", f: "Heading → Action" },
    { l: "TV Episode Outline", f: "Act → Beats" },
    { l: "Movie Treatment", f: "Character → Arc" },
    { l: "Comic Script", f: "Panel → Dialogue" },
    { l: "Manga Script", f: "Page → Frame" },
    { l: "Animation Script", f: "Scene → Voice Lines" },
    { l: "Video Script", f: "Segment → Narration" },
    { l: "Documentary Script", f: "Topic → Evidence" },
    { l: "Podcast Script", f: "Section → Conversation" },
    { l: "Audio Drama", f: "Scene → Sound Cues" },
    { l: "Interview Script", f: "Question → Follow-up" },
    { l: "Journalism Article", f: "Lead → Body" },
    { l: "News Story", f: "What → Why" },
    { l: "Opinion Column", f: "Claim → Arguments" },
    { l: "Review", f: "Summary → Critique" },
    { l: "Travel Blog", f: "Location → Experience" },
    { l: "Lifestyle Blog", f: "Topic → Tips" },
    { l: "How-To Article", f: "Step → Example" },
    { l: "Top-10 List", f: "Item → Explanation" },
    { l: "Personal Diary", f: "Day → Thoughts" },
    { l: "Memoir", f: "Memory → Lesson" },
    { l: "Poem", f: "Theme → Imagery" },
    { l: "Lyric Sheet", f: "Verse → Chorus" },
    { l: "Riddle", f: "Clue → Answer" },
    { l: "Fable", f: "Setup → Moral" },
    { l: "Children's Story", f: "Character → Situation" },
    { l: "Folktale", f: "Myth → Meaning" },
    { l: "Urban Legend", f: "Event → Suspense" },
    { l: "Horror Story", f: "Calm → Rising Dread" },
    { l: "Mystery Story", f: "Clue → Suspect" },
    { l: "Thriller Outline", f: "Tension → Escalation" },
    { l: "Fantasy Outline", f: "Kingdom → Quest" },
    { l: "Sci-Fi Outline", f: "Tech → Conflict" },
    { l: "Romance Outline", f: "Meeting → Tension" },
    { l: "Comedy Script", f: "Setup → Punchline" },
    { l: "Parody Script", f: "Reference → Twist" },
    { l: "Songwriting Plan", f: "Verse → Hook" },
    { l: "Music Album Concept", f: "Track → Emotion" },
    { l: "Speech Script", f: "Opening → Key Points" },
    { l: "Debate Script", f: "Claim → Rebuttal" },
    { l: "Interactive Story", f: "Choice → Outcome" },
    { l: "Podcast Outline", f: "Intro → Segment Topics" },
    { l: "Vlog Script", f: "Scene → Dialogue" },
    { l: "TikTok Script", f: "Hook → Punchline" },
    { l: "YouTube Video Guide", f: "Intro → Demonstration" },
    { l: "Fan Fiction", f: "Character → Conflict" },
    { l: "Story Prompt", f: "Setting → Situation" },
    { l: "Dialogue Draft", f: "Character → Lines" },
    { l: "Monologue", f: "Character → Emotion" },
    { l: "Flash Animation Script", f: "Scene → Motion" },
    { l: "Audio Guide", f: "Topic → Voice-over" },
    { l: "Voice-over Script", f: "Scene → Direction" },
    { l: "Multimedia Presentation", f: "Slide → Notes" },
    { l: "Web Comic Layout", f: "Panel → Action" },
    { l: "Concept Art Sheet", f: "Design → Description" },
    { l: "Short Film Plan", f: "Scene → Camera Angle" },
    { l: "Music Video Script", f: "Scene → Lyrics Sync" },
    { l: "Interactive Game Dialogue", f: "Prompt → Player Choice" },
    { l: "Alternate Ending Draft", f: "Scene → Resolution" },
    { l: "Storyboard Thumbnail", f: "Frame → Description" },
    { l: "Sketch Script", f: "Character → Pose" },
    { l: "Story Arc Map", f: "Event → Consequence" },
    { l: "Dialogue Editing Sheet", f: "Line → Revision" },
    { l: "Emotional Beats Sheet", f: "Scene → Tone" },
    { l: "Episode Summary", f: "Act → Key Event" },
    { l: "Conflict Mapping", f: "Character → Tension" },
    { l: "Mood Board Notes", f: "Visual → Feeling" },
    { l: "Media Pitch", f: "Concept → Hook" },
    { l: "Content Calendar", f: "Date → Content Idea" },
    { l: "Script Beat Sheet", f: "Beat → Timing" },
    { l: "Story Premise", f: "Hook → Twist" },
    { l: "Plot Skeleton", f: "Chapter → Event" },
    { l: "Cinematic Shot List", f: "Scene → Angle" },
    { l: "Voice Recording Script", f: "Segment → Instructions" },
    { l: "Sound Design Doc", f: "Scene → Sound Cue" },
    { l: "Animation Timing Sheet", f: "Frame → Action" },
    { l: "Story Outline", f: "Setting → Conflict" },
    { l: "Visual Narrative Plan", f: "Panel → Text" },
    { l: "Screen Direction Notes", f: "Actor → Movement" },
    { l: "Creative Prompt", f: "Idea → Expected Response" },
    { l: "Game Scenario", f: "Situation → Outcome" },
    { l: "Interactive Experience Plan", f: "Trigger → Reaction" },
    { l: "Character Dialogue Tree", f: "Choice → Response" },
    { l: "Script Annotation", f: "Line → Emotion" },
    { l: "Scene Breakdown", f: "Event → Visual Cue" },
    { l: "Story Flowchart", f: "Event → Next Step" },
    { l: "Media Review", f: "Work → Opinion" },
    { l: "Story Revisions Log", f: "Draft → Changes" },
    { l: "Scene Idea Log", f: "Concept → Note" },
    { l: "Episode Plot", f: "Act → Climax" },
    { l: "Audio Editing Sheet", f: "Clip → Effect" },
    { l: "Screenplay Outline", f: "Scene → Purpose" },
    { l: "Character Arc Tracker", f: "Scene → Growth" },
    { l: "Fantasy Map Plan", f: "Region → Feature" },
    { l: "Sci-Fi World Doc", f: "Planet → Rule" },
    { l: "Horror Scene Plan", f: "Event → Tension" },
    { l: "Romance Plot Tracker", f: "Scene → Emotional Beat" },
    { l: "Comedy Sketch", f: "Setup → Punchline" },
    { l: "Satire Piece", f: "Target → Twist" },
    { l: "Dramatic Scene", f: "Conflict → Resolution" },
    { l: "Short Story Plot", f: "Beginning → Climax" },
    { l: "Story Idea Bank", f: "Prompt → Notes" },
    { l: "Film Shot List", f: "Scene → Angle" },
    { l: "Dialogue Revision Tracker", f: "Line → Notes" },
    { l: "Scene Mood Board", f: "Visual → Emotion" },
    { l: "Voice Acting Notes", f: "Character → Delivery" },
    { l: "Animation Asset Sheet", f: "Object → Action" },
    { l: "Music Scoring Plan", f: "Scene → Mood" },
    { l: "Soundtrack Cue Sheet", f: "Track → Scene" },
    { l: "Interactive Script", f: "Choice → Branch" }
];
