export const EDUCATION_TEACHING = [
    { l: "Course Syllabus", f: "Topic → Weekly Plan" },
    { l: "Lesson Plan", f: "Objective → Activities" },
    { l: "Curriculum Outline", f: "Module → Competency" },
    { l: "Study Guide", f: "Topic → Key Notes" },
    { l: "Worksheet", f: "Concept → Practice Questions" },
    { l: "Exam Paper", f: "Section → Questions" },
    { l: "Answer Sheet", f: "Question → Explanation" },
    { l: "Quiz", f: "Question → Options" },
    { l: "Flashcards", f: "Term → Definition" },
    { l: "Workbook Chapter", f: "Theory → Exercises" },
    { l: "Teacher’s Guide", f: "Lesson → Tips" },
    { l: "Rubric", f: "Criteria → Scoring" },
    { l: "Educational Poster", f: "Topic → Key Points" },
    { l: "Science Fair Report", f: "Problem → Method" },
    { l: "Student Portfolio", f: "Project → Reflection" },
    { l: "Project Rubric", f: "Requirement → Score" },
    { l: "Class Rules", f: "Category → Guidelines" },
    { l: "Reading Log", f: "Book → Reflection" },
    { l: "Academic Progress Report", f: "Subject → Comments" },
    { l: "Internship Report", f: "Task → Learning" },
    { l: "Field Trip Report", f: "Place → Observations" },
    { l: "Journal Entry", f: "Event → Reflection" },
    { l: "Research Notebook", f: "Date → Notes" },
    { l: "Debate Outline", f: "Point → Evidence" },
    { l: "Seminar Notes", f: "Topic → Interpretation" },
    { l: "Presentation Slides", f: "Title → Points" },
    { l: "Academic Poster", f: "Section → Visual" },
    { l: "Thesis Defense Slides", f: "Claim → Evidence" },
    { l: "Student Feedback Form", f: "Question → Response" },
    { l: "Peer Evaluation", f: "Work → Comments" },
    { l: "Homework Sheet", f: "Task → Instructions" },
    { l: "Group Project Plan", f: "Roles → Tasks" },
    { l: "Capstone Proposal", f: "Topic → Plan" },
    { l: "Case Method", f: "Scenario → Questions" },
    { l: "Literacy Plan", f: "Skill → Practice" },
    { l: "Math Problem Set", f: "Topic → Exercises" },
    { l: "Lab Worksheet", f: "Setup → Observations" },
    { l: "Reading Comprehension", f: "Passage → Questions" },
    { l: "Annotated Text", f: "Line → Interpretation" },
    { l: "Spelling List", f: "Word → Definition" },
    { l: "Vocabulary Builder", f: "Word → Usage" },
    { l: "Grammar Exercise", f: "Rule → Task" },
    { l: "Essay Planner", f: "Claim → Structure" },
    { l: "Revision Plan", f: "Weakness → Action" },
    { l: "Study Roadmap", f: "Chapter → Timeline" },
    { l: "Learning Contract", f: "Goal → Milestone" },
    { l: "Peer Tutoring Sheet", f: "Topic → Notes" },
    { l: "Learning Summary", f: "Week → Insights" },
    { l: "Knowledge Map", f: "Topic → Connections" },
    { l: "Educational Module", f: "Lesson → Assessment" }
];