
export const FASHION_LIFESTYLE = [
    { l: "Fashion Collection Plan", f: "Season → Piece" },
    { l: "Style Guide", f: "Occasion → Outfit" },
    { l: "Trend Forecast Report", f: "Year → Trend" },
    { l: "Fashion Show Schedule", f: "Model → Outfit" },
    { l: "Wardrobe Inventory", f: "Item → Quantity" },
    { l: "Styling Notes", f: "Model → Accessory" },
    { l: "Fashion Design Sketch", f: "Piece → Detail" },
    { l: "Lifestyle Blog Post", f: "Topic → Story" },
    { l: "Outfit Coordination Plan", f: "Occasion → Step" },
    { l: "Accessory Design Sheet", f: "Item → Detail" },
    { l: "Fashion Photography Shot List", f: "Scene → Pose" },
    { l: "Fashion Marketing Plan", f: "Campaign → Channel" },
    { l: "Lookbook Layout", f: "Outfit → Page" },
    { l: "Styling Consultation Notes", f: "Client → Suggestion" },
    { l: "Fashion Event Proposal", f: "Theme → Activity" },
    { l: "Trend Analysis Dashboard", f: "Trend → Metric" },
    { l: "Clothing Line Production Timeline", f: "Piece → Step" },
    { l: "Fashion Budget Planner", f: "Item → Cost" },
    { l: "Model Casting Notes", f: "Model → Detail" },
    { l: "Fashion Workshop Agenda", f: "Topic → Activity" },
    { l: "Outfit Styling Checklist", f: "Item → Status" },
    { l: "Accessory Collection Plan", f: "Item → Material" },
    { l: "Fashion Editorial Plan", f: "Topic → Article" },
    { l: "Lifestyle Video Script", f: "Scene → Action" },
    { l: "Fashion Show Run Sheet", f: "Sequence → Detail" },
    { l: "Model Schedule Tracker", f: "Model → Time" },
    { l: "Style Inspiration Board", f: "Theme → Image" },
    { l: "Fashion Production Notes", f: "Piece → Observation" },
    { l: "Wardrobe Planning Template", f: "Occasion → Outfit" },
    { l: "Styling Portfolio", f: "Client → Outfit" },
    { l: "Trend Research Notes", f: "Topic → Observation" },
    { l: "Fashion Campaign Metrics", f: "Channel → Result" },
    { l: "Fashion Blog Editorial Calendar", f: "Date → Post" },
    { l: "Accessory Design Timeline", f: "Item → Step" },
    { l: "Fashion Photography Plan", f: "Location → Shot" },
    { l: "Outfit Feedback Form", f: "Item → Rating" },
    { l: "Fashion Sketch Revisions", f: "Piece → Update" },
    { l: "Lifestyle Newsletter", f: "Topic → Article" },
    { l: "Fashion Show Layout", f: "Stage → Element" },
    { l: "Model Measurement Sheet", f: "Model → Size" },
    { l: "Fashion Event Evaluation", f: "Activity → Outcome" },
    { l: "Style Consultation Template", f: "Client → Step" },
    { l: "Fashion Product Development Plan", f: "Piece → Feature" },
    { l: "Trend Presentation Deck", f: "Slide → Content" },
    { l: "Fashion Resource Inventory", f: "Item → Quantity" },
    { l: "Lifestyle Magazine Article", f: "Topic → Paragraph" },
    { l: "Fashion Campaign Proposal", f: "Channel → Goal" },
    { l: "Model Runway Notes", f: "Model → Walk" },
    { l: "Fashion Workshop Materials", f: "Item → Quantity" },
    { l: "Outfit Coordination Feedback", f: "Item → Comment" },
    { l: "Accessory Styling Notes", f: "Item → Observation" },
    { l: "Fashion Show Photographer Plan", f: "Scene → Shot" },
    { l: "Clothing Line Production Notes", f: "Piece → Detail" },
    { l: "Fashion Trend Report Archive", f: "Year → Trend" },
    { l: "Style Guide Update", f: "Occasion → Outfit" },
    { l: "Fashion Product Feedback Form", f: "Product → Rating" },
    { l: "Lifestyle Video Production Timeline", f: "Scene → Action" },
    { l: "Fashion Illustration Archive", f: "Piece → Sketch" },
    { l: "Model Casting Schedule", f: "Model → Time" },
    { l: "Fashion Collection Launch Plan", f: "Piece → Date" },
    { l: "Outfit Styling Workshop Agenda", f: "Topic → Step" },
    { l: "Accessory Production Checklist", f: "Item → Status" },
    { l: "Fashion Editorial Layout Plan", f: "Page → Content" },
    { l: "Lifestyle Blog Post Calendar", f: "Date → Topic" },
    { l: "Trend Analysis Notes", f: "Year → Observation" }
];
