
export const SCIFI_FANTASY = [
    { l: "Story Universe Outline", f: "Region → Description" },
    { l: "Character Development Sheet", f: "Character → Trait" },
    { l: "Plot Arc Template", f: "Chapter → Event" },
    { l: "Magic System Guide", f: "Spell → Effect" },
    { l: "Sci-Fi Technology Document", f: "Device → Function" },
    { l: "Alien Species Profile", f: "Species → Characteristic" },
    { l: "World-Building Notes", f: "Location → Detail" },
    { l: "Quest Design Plan", f: "Objective → Step" },
    { l: "Villain Profile", f: "Name → Motivation" },
    { l: "Hero Journey Map", f: "Stage → Challenge" },
    { l: "Chapter Synopsis", f: "Chapter → Summary" },
    { l: "Fantasy Creature Manual", f: "Creature → Ability" },
    { l: "Sci-Fi Vehicle Blueprint", f: "Vehicle → Feature" },
    { l: "Magic Artifact Sheet", f: "Artifact → Power" },
    { l: "Scene Description Template", f: "Scene → Detail" },
    { l: "Dialogue Draft", f: "Character → Line" },
    { l: "Storyboard Layout", f: "Panel → Action" },
    { l: "World Map Annotation", f: "Region → Feature" },
    { l: "Character Relationship Chart", f: "Character → Connection" },
    { l: "Quest Item List", f: "Item → Function" },
    { l: "Chapter Outline Notes", f: "Chapter → Detail" },
    { l: "Technology Design Log", f: "Device → Specification" },
    { l: "Creature Encounter Template", f: "Creature → Scene" },
    { l: "Magic Spellbook Entry", f: "Spell → Effect" },
    { l: "Story Theme Analysis", f: "Theme → Example" },
    { l: "Plot Twist Tracker", f: "Event → Outcome" },
    { l: "Dialogue Revision Notes", f: "Scene → Change" },
    { l: "World History Timeline", f: "Era → Event" },
    { l: "Planetary Description Sheet", f: "Planet → Detail" },
    { l: "Hero Skill Tracker", f: "Skill → Level" },
    { l: "Fantasy Location Guide", f: "Location → Description" },
    { l: "Sci-Fi Mission Plan", f: "Objective → Step" },
    { l: "Magical Item Inventory", f: "Item → Quantity" },
    { l: "Alien Planet Ecosystem Notes", f: "Species → Interaction" },
    { l: "Scene Setting Notes", f: "Scene → Detail" },
    { l: "Character Motivation Log", f: "Character → Reason" },
    { l: "Plot Development Tracker", f: "Chapter → Event" },
    { l: "Creature Ability Tracker", f: "Creature → Power" },
    { l: "Spell Effects Table", f: "Spell → Outcome" },
    { l: "Sci-Fi World Blueprint", f: "Sector → Feature" },
    { l: "Story Revision Log", f: "Chapter → Update" },
    { l: "Dialogue Flowchart", f: "Character → Line" },
    { l: "Quest Progress Tracker", f: "Quest → Stage" },
    { l: "Artifact Location Map", f: "Artifact → Place" },
    { l: "Character Backstory Notes", f: "Character → Detail" },
    { l: "Sci-Fi Device Testing Notes", f: "Device → Result" },
    { l: "Fantasy Creature Interaction Log", f: "Creature → Event" },
    { l: "Scene Mood Board", f: "Scene → Visual" },
    { l: "Hero Inventory Sheet", f: "Item → Effect" },
    { l: "Plot Line Map", f: "Chapter → Event" },
    { l: "Character Appearance Notes", f: "Character → Detail" },
    { l: "Magic System Rules", f: "Rule → Explanation" },
    { l: "Story Conflict Tracker", f: "Conflict → Resolution" },
    { l: "World-Building Reference Sheet", f: "Element → Detail" },
    { l: "Chapter Dialogue Notes", f: "Scene → Character" },
    { l: "Sci-Fi Alien Technology Notes", f: "Device → Feature" },
    { l: "Fantasy Quest Timeline", f: "Quest → Stage" },
    { l: "Magical Creature Abilities", f: "Creature → Description" },
    { l: "Story Event Tracker", f: "Event → Outcome" },
    { l: "Dialogue Characterization Notes", f: "Character → Trait" },
    { l: "Plot Arc Revision", f: "Chapter → Adjustment" },
    { l: "World Region Notes", f: "Region → Detail" },
    { l: "Story Beat Sheet", f: "Scene → Action" },
    { l: "Fantasy Artifact Creation", f: "Artifact → Detail" },
    { l: "Hero Character Arc Notes", f: "Character → Development" },
    { l: "Sci-Fi Mission Log", f: "Objective → Status" },
    { l: "Magical Spell Revision Notes", f: "Spell → Update" },
    { l: "Creature Encounter Timeline", f: "Creature → Scene" },
    { l: "Story Theme Tracker", f: "Theme → Chapter" },
    { l: "Plot Development Notes", f: "Chapter → Event" }
];
