
export const TECHNOLOGY_INNOVATION = [
    { l: "Product Roadmap", f: "Feature → Timeline" },
    { l: "Software Design Document", f: "Module → Function" },
    { l: "Technology Research Proposal", f: "Hypothesis → Method" },
    { l: "Innovation Pitch Deck", f: "Slide → Content" },
    { l: "Prototype Development Plan", f: "Component → Step" },
    { l: "System Architecture Diagram", f: "Component → Connection" },
    { l: "Technical Specification Sheet", f: "Feature → Detail" },
    { l: "Patent Application", f: "Invention → Claim" },
    { l: "R&D Experiment Log", f: "Test → Observation" },
    { l: "Technology Whitepaper", f: "Topic → Analysis" },
    { l: "Software Testing Plan", f: "Module → Test Case" },
    { l: "Bug Tracking Report", f: "Bug → Status" },
    { l: "Development Sprint Plan", f: "Task → Deadline" },
    { l: "Technical Feasibility Report", f: "System → Evaluation" },
    { l: "User Flow Diagram", f: "Step → Decision" },
    { l: "Technology Trend Analysis", f: "Field → Insight" },
    { l: "Innovation Impact Assessment", f: "Solution → Effect" },
    { l: "Prototype Testing Notes", f: "Feature → Result" },
    { l: "Software Release Notes", f: "Version → Changes" },
    { l: "API Documentation", f: "Endpoint → Description" },
    { l: "User Guide", f: "Function → Instruction" },
    { l: "Technical Memo", f: "Topic → Recommendation" },
    { l: "Product Specification", f: "Attribute → Value" },
    { l: "Development Retrospective", f: "Sprint → Lesson" },
    { l: "System Integration Plan", f: "Component → Step" },
    { l: "Tech Workshop Agenda", f: "Session → Activity" },
    { l: "Innovation Benchmark Report", f: "Solution → Score" },
    { l: "Software Architecture Review", f: "Module → Finding" },
    { l: "Technical Risk Assessment", f: "Factor → Mitigation" },
    { l: "Hardware Design Notes", f: "Component → Specification" },
    { l: "Technology Policy Document", f: "Rule → Application" },
    { l: "Prototype Demonstration Plan", f: "Step → Action" },
    { l: "Technical Review Notes", f: "Feature → Observation" },
    { l: "Software Bug Fix Log", f: "Bug → Resolution" },
    { l: "Development Timeline", f: "Phase → Task" },
    { l: "System Requirement Specification", f: "Requirement → Detail" },
    { l: "Innovation Grant Proposal", f: "Project → Budget" },
    { l: "Technology Presentation Script", f: "Slide → Talking Point" },
    { l: "Technical Feasibility Checklist", f: "Task → Status" },
    { l: "Prototype Evaluation Report", f: "Component → Result" },
    { l: "Technology Implementation Plan", f: "Step → Responsible" },
    { l: "Coding Standards Document", f: "Rule → Example" },
    { l: "Product Backlog", f: "Item → Priority" },
    { l: "Development Workflow Chart", f: "Step → Next Step" },
    { l: "Software Test Case Sheet", f: "Case → Expected Result" },
    { l: "System Performance Metrics", f: "Metric → Value" },
    { l: "Technical Training Material", f: "Topic → Module" },
    { l: "Innovation Strategy Document", f: "Goal → Action" },
    { l: "Technology Requirements Analysis", f: "Requirement → Detail" },
    { l: "Prototype Feedback Form", f: "Feature → Comment" },
    { l: "Technical Risk Log", f: "Issue → Impact" },
    { l: "Software Maintenance Plan", f: "Task → Frequency" },
    { l: "API Testing Notes", f: "Endpoint → Status" },
    { l: "Development Resource Allocation", f: "Task → Resource" },
    { l: "Technical Whiteboard Notes", f: "Topic → Diagram" },
    { l: "System Deployment Plan", f: "Component → Step" },
    { l: "Technology Trend Forecast", f: "Field → Projection" },
    { l: "Innovation Case Study", f: "Solution → Result" },
    { l: "Prototype Iteration Plan", f: "Feature → Change" },
    { l: "Software Version Control Log", f: "Commit → Description" },
    { l: "Product Usability Test", f: "Task → Observation" },
    { l: "Technical Checklist", f: "Task → Completion" },
    { l: "Development Bug Report", f: "Bug → Status" },
    { l: "Technology Risk Mitigation Plan", f: "Risk → Action" },
    { l: "Prototype Roadmap", f: "Feature → Timeline" },
    { l: "System Configuration Guide", f: "Component → Setting" },
    { l: "Innovation Pitch Notes", f: "Slide → Talking Point" },
    { l: "Software Deployment Notes", f: "Step → Outcome" },
    { l: "Technical Review Checklist", f: "Item → Status" },
    { l: "Technology Performance Dashboard", f: "Metric → Value" },
    // New additions
    { l: "Product Development Notes", f: "Feature → Step" },
    { l: "Innovation Roadmap", f: "Milestone → Deadline" },
    { l: "Patent Filing Template", f: "Invention → Detail" },
    { l: "Tech Research Paper", f: "Section → Content" },
    { l: "Prototype Testing Log", f: "Component → Result" },
    { l: "Software Architecture Diagram", f: "Module → Connection" },
    { l: "Technical Feasibility Study", f: "Task → Outcome" },
    { l: "Technology Stack Overview", f: "Layer → Tool" },
    { l: "System Design Notes", f: "Module → Specification" },
    { l: "R&D Project Proposal", f: "Objective → Method" },
    { l: "Technical Evaluation Form", f: "Metric → Score" },
    { l: "Innovation Metrics Tracker", f: "Metric → Value" },
    { l: "Prototype Revision Notes", f: "Component → Change" },
    { l: "Technology Implementation Plan", f: "Task → Step" },
    { l: "Technical Workshop Agenda", f: "Topic → Activity" },
    { l: "Innovation Case Study", f: "Example → Analysis" },
    { l: "Product Feature Specification", f: "Feature → Detail" },
    { l: "Software Testing Checklist", f: "Test → Status" },
    { l: "Technology Trend Report", f: "Trend → Analysis" },
    { l: "R&D Budget Planner", f: "Project → Cost" }
];
